// eslint-disable-next-line import/no-anonymous-default-export
export default [
    // SOFTWARE ROADMAPS (10)
    {
        id: '1',
        title: 'Java Developer Roadmap',
        desc: 'Covers Java from basics to advanced concepts like OOPS, DSA, Spring Boot, Microservices, and Deployment.',
        level: 5,
        tags: ['JAVA', 'Spring', 'OOPS'],
        ig: 'Software',
        learners: 251,
    },
    {
        id: '2',
        title: 'Full-Stack Web Development',
        desc: 'Master HTML, CSS, JavaScript, React, Node.js, Express, MongoDB, and DevOps.',
        level: 5,
        tags: ['Web', 'React', 'Node.js'],
        ig: 'Software',
        learners: 430,
    },
    {
        id: '3',
        title: 'Python for Data Science',
        desc: 'Learn Python, Pandas, NumPy, Matplotlib, Scikit-learn, and Machine Learning fundamentals.',
        level: 4,
        tags: ['Python', 'Data Science', 'ML'],
        ig: 'Software',
        learners: 370,
    },
    // {
    //     id: '4',
    //     title: 'Cybersecurity Fundamentals',
    //     desc: 'Understand cybersecurity principles, ethical hacking, penetration testing, and network security.',
    //     level: 5,
    //     tags: ['Cybersecurity', 'Hacking', 'Networking'],
    //     ig: 'Software',
    //     learners: 215,
    // },
    {
        id: '5',
        title: 'Game Development with Unity',
        desc: 'Learn Unity engine, C# scripting, 2D & 3D game mechanics, and deployment.',
        level: 4,
        tags: ['Unity', 'Game Dev', 'C#'],
        ig: 'Software',
        learners: 300,
    },
    // {
    //     id: '6',
    //     title: 'Blockchain Development',
    //     desc: 'Explore blockchain technology, smart contracts, Ethereum, and Web3 development.',
    //     level: 5,
    //     tags: ['Blockchain', 'Web3', 'Smart Contracts'],
    //     ig: 'Software',
    //     learners: 180,
    // },
    // {
    //     id: '7',
    //     title: 'iOS App Development',
    //     desc: 'Build iOS apps using Swift, SwiftUI, Core Data, and integrate APIs.',
    //     level: 4,
    //     tags: ['Swift', 'iOS', 'Xcode'],
    //     ig: 'Software',
    //     learners: 220,
    // },
    // {
    //     id: '8',
    //     title: 'Android App Development',
    //     desc: 'Learn Kotlin, Jetpack Compose, MVVM architecture, and Firebase integration.',
    //     level: 4,
    //     tags: ['Kotlin', 'Android', 'Mobile'],
    //     ig: 'Software',
    //     learners: 250,
    // },
    // {
    //     id: '9',
    //     title: 'Cloud Computing & DevOps',
    //     desc: 'Master AWS, Docker, Kubernetes, CI/CD, and serverless architecture.',
    //     level: 5,
    //     tags: ['AWS', 'DevOps', 'Cloud'],
    //     ig: 'Software',
    //     learners: 320,
    // },
    // {
    //     id: '10',
    //     title: 'AI & Machine Learning',
    //     desc: 'Deep dive into AI, TensorFlow, deep learning, NLP, and neural networks.',
    //     level: 5,
    //     tags: ['AI', 'ML', 'TensorFlow'],
    //     ig: 'Software',
    //     learners: 410,
    // },

    // // HARDWARE ROADMAPS (10)
    // {
    //     id: '11',
    //     title: 'Embedded Systems Development',
    //     desc: 'Learn microcontrollers, ARM architecture, and real-time OS programming.',
    //     level: 4,
    //     tags: ['Embedded', 'Microcontrollers', 'C'],
    //     ig: 'Hardware',
    //     learners: 180,
    // },
    // {
    //     id: '12',
    //     title: 'IoT Development',
    //     desc: 'Build IoT systems with Raspberry Pi, Arduino, MQTT, and sensor networks.',
    //     level: 5,
    //     tags: ['IoT', 'Arduino', 'Raspberry Pi'],
    //     ig: 'Hardware',
    //     learners: 250,
    // },
    // {
    //     id: '13',
    //     title: 'VLSI Design',
    //     desc: 'Introduction to FPGA, ASIC design, and hardware description languages like Verilog.',
    //     level: 5,
    //     tags: ['VLSI', 'Verilog', 'FPGA'],
    //     ig: 'Hardware',
    //     learners: 140,
    // },
    // {
    //     id: '14',
    //     title: 'Robotics & Automation',
    //     desc: 'Learn robotic kinematics, AI in robotics, ROS, and control systems.',
    //     level: 5,
    //     tags: ['Robotics', 'AI', 'ROS'],
    //     ig: 'Hardware',
    //     learners: 190,
    // },

    // // MANAGEMENT ROADMAPS (10)
    // {
    //     id: '21',
    //     title: 'MBA Essentials',
    //     desc: 'Introduction to business strategy, finance, marketing, and operations.',
    //     level: 4,
    //     tags: ['Business', 'MBA', 'Finance'],
    //     ig: 'Management',
    //     learners: 310,
    // },
    // {
    //     id: '22',
    //     title: 'Product Management',
    //     desc: 'Learn product strategy, roadmaps, user research, and Agile development.',
    //     level: 4,
    //     tags: ['Product', 'Agile', 'User Research'],
    //     ig: 'Management',
    //     learners: 270,
    // },

    // // CREATIVE ROADMAPS (10)
    // {
    //     id: '31',
    //     title: 'UI/UX Design',
    //     desc: 'Master Figma, Adobe XD, wireframing, and user research.',
    //     level: 4,
    //     tags: ['UI/UX', 'Design', 'Figma'],
    //     ig: 'Creative',
    //     learners: 260,
    // },
    // {
    //     id: '32',
    //     title: 'Graphic Design Mastery',
    //     desc: 'Learn Photoshop, Illustrator, typography, and brand identity design.',
    //     level: 3,
    //     tags: ['Graphic Design', 'Photoshop', 'Branding'],
    //     ig: 'Creative',
    //     learners: 180,
    // },
    // {
    //     id: '33',
    //     title: 'Filmmaking & Video Production',
    //     desc: 'Learn cinematography, video editing, scriptwriting, and production techniques.',
    //     level: 5,
    //     tags: ['Filmmaking', 'Cinematography', 'Editing'],
    //     ig: 'Creative',
    //     learners: 220,
    // },
    // {
    //     id: '34',
    //     title: 'Animation & Motion Graphics',
    //     desc: 'Explore 2D/3D animation, After Effects, Blender, and motion design principles.',
    //     level: 5,
    //     tags: ['Animation', 'Blender', 'After Effects'],
    //     ig: 'Creative',
    //     learners: 170,
    // },
    // {
    //     id: '35',
    //     title: 'Game Art & Design',
    //     desc: 'Understand game aesthetics, 3D modeling, texturing, and game asset creation.',
    //     level: 5,
    //     tags: ['Game Design', '3D Modeling', 'Art'],
    //     ig: 'Creative',
    //     learners: 210,
    // },
    // {
    //     id: '36',
    //     title: 'Music Production & Sound Design',
    //     desc: 'Learn digital audio production, sound engineering, and mixing techniques.',
    //     level: 5,
    //     tags: ['Music Production', 'Audio', 'Mixing'],
    //     ig: 'Creative',
    //     learners: 160,
    // }
];
