export const roles = {
    ADMIN: "Admins",
    DISCORD_MODERATOR: "Discord Moderator",
    EX_OFFICIAL: "Ex Official",
    FELLOW: "Fellow",
    ZONAL_CAMPUS_LEAD: "Zonal Campus Lead",
    APPRAISER: "Appraiser",
    DISTRICT_CAMPUS_LEAD: "District Campus Lead",
    MENTOR: "Mentor",
    INTERN: "Intern",
    CAMPUS_LEAD: "Campus Lead",
    BOT_DEV: "Bot Dev",
    PRE_MEMBER: "Pre Member",
    SUSPEND: "Suspended",
    STUDENT: "Student",
    ENABLER: "Enabler",
    IG_FACILITATOR: "IG Facilitator",
    TECH_TEAM: "Tech Team",
    ASSOCIATE: "Associate",
    CAMPUS_ACTIVATION_TEAM: "Campus Activation Team",
    LEAD_ENABLER: "Lead Enabler"
} as const;

export const managementTypes = {
    CAMPUS: 'Campus',
    HACKATHON: 'Hackathon',
    USER_MANAGEMENT: 'User Management',
    MANAGE_ORGANIZATION: 'Manage Organization',
    TASK_MANAGEMENT: 'Task Management',
    INTEREST_GROUP: 'Interest Group',
    COLLEGE_LEVELS: 'College Levels',
    KARMA_VOUCHER: 'Karma Voucher',
    ERROR_LOG: 'Error Log',
    DYNAMIC_TYPE: 'Dynamic Type',
    MANAGE_ROLES: 'Manage Roles',
    MANAGE_LOCATIONS: 'Manage Locations',
    CHANNELS: 'Channels',
    URL_SHORTENER: 'Url Shortener',
    DISCORD_MODERATION: 'Discord Moderation'
} as const