export const levelsDataWebDev = [
  {
    "level": 4,
    "title": "Level 4",
    "subtitle": "Master Web Fundamentals with HTML & CSS",
    "cards": [
      {
        "id": "4-1",
        "title": "Cat Photo App",
        "desc": "Build a basic website to display cat photos. Focus on HTML fundamentals, image embedding, and simple responsive design.",
        "brief": "Create a webpage using HTML to structure cat photo content and CSS for styling and responsiveness. Submit a hosted link or code repository.",
        "karma": 200,
        "hashtag": "#cl-catphoto",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdImage />",
        "skills": ["HTML Structure", "CSS Styling", "Responsive Design"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 10:00 AM",
        "prerequisites": ["Basic understanding of web browsers"],
        "resources": ["https://developer.mozilla.org/en-US/docs/Web/HTML"]
      },
      {
        "id": "4-2",
        "title": "Format Letter Online",
        "desc": "Create HTML templates for different types of letters (personal, business, etc.). Practice basic HTML structure and CSS styling.",
        "brief": "Design at least two letter templates (e.g., personal and business) using HTML and CSS. Submit a hosted link or code repository.",
        "karma": 200,
        "hashtag": "#cl-formatletter",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdTextFields />",
        "skills": ["HTML Semantics", "CSS Layout", "Typography"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 10:10 AM",
        "prerequisites": ["Basic HTML knowledge"],
        "resources": ["https://www.w3schools.com/html/"]
      },
      {
        "id": "4-3",
        "title": "Master Building Block",
        "desc": "Build small, reusable CSS components like buttons and navigation menus.",
        "brief": "Create at least three reusable CSS components (e.g., button, nav menu, card). Submit a hosted link or code repository.",
        "karma": 250,
        "hashtag": "#cl-buildingblock",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdBrush />",
        "skills": ["CSS Styling", "Component Design", "Responsive Design"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 10:20 AM",
        "prerequisites": ["Basic CSS knowledge"],
        "resources": ["https://css-tricks.com/"]
      },
      {
        "id": "4-4",
        "title": "Redesign Website",
        "desc": "Revamp an existing website using HTML and CSS, focusing on modern design principles.",
        "brief": "Choose a simple website and redesign it with HTML and CSS. Submit before/after hosted links or code repository.",
        "karma": 300,
        "hashtag": "#cl-redesignwebsite",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdWeb />",
        "skills": ["HTML Structure", "CSS Styling", "Accessibility"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 10:30 AM",
        "prerequisites": ["Basic HTML and CSS"],
        "resources": ["https://www.smashingmagazine.com/"]
      },
      {
        "id": "4-5",
        "title": "Style Biography",
        "desc": "Design visually engaging biography templates with CSS.",
        "brief": "Create a biography page with HTML and styled with CSS, including one interactive element. Submit a hosted link or code repository.",
        "karma": 250,
        "hashtag": "#cl-stylebio",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdPerson />",
        "skills": ["CSS Typography", "Layout Design", "Interactivity"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 10:40 AM",
        "prerequisites": ["Basic HTML and CSS"],
        "resources": ["https://www.w3schools.com/css/"]
      },
      {
        "id": "4-6",
        "title": "Embed Experience",
        "desc": "Enhance web pages with multimedia (images, videos, audio).",
        "brief": "Build a webpage embedding at least one image, video, and audio, styled with CSS. Submit a hosted link or code repository.",
        "karma": 200,
        "hashtag": "#cl-embedexp",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdVideoLibrary />",
        "skills": ["HTML Media", "CSS Styling", "Accessibility"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 10:50 AM",
        "prerequisites": ["Basic HTML and CSS"],
        "resources": ["https://developer.mozilla.org/en-US/docs/Web/Media"]
      },
      {
        "id": "4-7",
        "title": "Style Word",
        "desc": "Explore creative typography using CSS for unique text styles.",
        "brief": "Create a webpage showcasing at least three unique text styles using CSS. Submit a hosted link or code repository.",
        "karma": 200,
        "hashtag": "#cl-styleword",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdTextFields />",
        "skills": ["CSS Typography", "Text Styling"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 11:00 AM",
        "prerequisites": ["Basic CSS"],
        "resources": ["https://fonts.google.com/"]
      },
      {
        "id": "4-8",
        "title": "Perfect Form",
        "desc": "Create user-friendly and accessible forms styled with CSS.",
        "brief": "Design a form with at least three input types, styled with CSS, ensuring accessibility. Submit a hosted link or code repository.",
        "karma": 250,
        "hashtag": "#cl-perfectform",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdInput />",
        "skills": ["HTML Forms", "CSS Styling", "Accessibility"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 11:10 AM",
        "prerequisites": ["Basic HTML and CSS"],
        "resources": ["https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form"]
      },
      {
        "id": "4-9",
        "title": "Tables",
        "desc": "Design responsive and well-structured tables using HTML and CSS.",
        "brief": "Create a responsive table with at least five rows and three columns, styled with CSS. Submit a hosted link or code repository.",
        "karma": 200,
        "hashtag": "#cl-tables",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdTableChart />",
        "skills": ["HTML Tables", "CSS Styling", "Responsive Design"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 11:20 AM",
        "prerequisites": ["Basic HTML and CSS"],
        "resources": ["https://www.w3schools.com/html/html_tables.asp"]
      },
      {
        "id": "4-10",
        "title": "Layouts",
        "desc": "Master CSS layout techniques like Flexbox and Grid.",
        "brief": "Build a webpage using Flexbox and Grid layouts, demonstrating responsiveness. Submit a hosted link or code repository.",
        "karma": 300,
        "hashtag": "#cl-layouts",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdGridOn />",
        "skills": ["Flexbox", "CSS Grid", "Responsive Design"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 11:30 AM",
        "prerequisites": ["Intermediate CSS knowledge"],
        "resources": ["https://css-tricks.com/snippets/css/a-guide-to-flexbox/"]
      }
    ]
  },
  {
    "level": 5,
    "title": "Level 5",
    "subtitle": "Add Interactivity with JavaScript",
    "cards": [
      {
        "id": "5-1",
        "title": "Story Generator Project",
        "desc": "Focuses on interactive storytelling using JavaScript.",
        "brief": "Build a webpage where users input data to generate a story, using HTML, CSS, and JavaScript. Submit a hosted link or code repository.",
        "karma": 300,
        "hashtag": "#cl-storygenerator",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdBook />",
        "skills": ["JavaScript Basics", "DOM Manipulation", "Event Handling"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 11:40 AM",
        "prerequisites": ["Basic HTML and CSS"],
        "resources": ["https://javascript.info/"]
      },
      {
        "id": "5-2",
        "title": "Building Blocks Project",
        "desc": "Creates reusable JavaScript components and utilities.",
        "brief": "Develop at least two reusable JavaScript components (e.g., modal, form validator). Submit a hosted link or code repository.",
        "karma": 350,
        "hashtag": "#cl-jsbuildingblocks",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdLayers />",
        "skills": ["JavaScript Functions", "Modular Code", "Event Handling"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 11:50 AM",
        "prerequisites": ["Basic JavaScript"],
        "resources": ["https://developer.mozilla.org/en-US/docs/Web/JavaScript"]
      },
      {
        "id": "5-3",
        "title": "Objects Project",
        "desc": "Deep dive into JavaScript object-oriented programming.",
        "brief": "Create a project using JavaScript objects (e.g., a simple game or inventory system). Submit a hosted link or code repository.",
        "karma": 350,
        "hashtag": "#cl-jsobjects",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdCategory />",
        "skills": ["JavaScript Objects", "ES6 Classes", "Data Manipulation"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 12:00 PM",
        "prerequisites": ["Intermediate JavaScript"],
        "resources": ["https://www.freecodecamp.org/news/object-oriented-javascript-for-beginners/"]
      },
      {
        "id": "5-4",
        "title": "Asynchronous Programming Project",
        "desc": "Explores handling concurrent operations in JavaScript.",
        "brief": "Build a project fetching data from an API using async JavaScript (e.g., weather app). Submit a hosted link or code repository.",
        "karma": 400,
        "hashtag": "#cl-jsasync",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdTimer />",
        "skills": ["Promises", "Async/Await", "API Integration"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 12:10 PM",
        "prerequisites": ["Intermediate JavaScript"],
        "resources": ["https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises"]
      },
      {
        "id": "5-5",
        "title": "Client-Side Web APIs Project",
        "desc": "Works with browser-based APIs like geolocation and storage.",
        "brief": "Create a project using at least one browser API (e.g., geolocation tracker). Submit a hosted link or code repository.",
        "karma": 400,
        "hashtag": "#cl-jswebapis",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdApi />",
        "skills": ["JavaScript APIs", "DOM Manipulation", "Error Handling"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 12:20 PM",
        "prerequisites": ["Intermediate JavaScript"],
        "resources": ["https://developer.mozilla.org/en-US/docs/Web/API"]
      }
    ]
  },
  {
    "level": 6,
    "title": "Level 6",
    "subtitle": "Build Advanced Web Applications",
    "cards": [
      {
        "id": "6-1",
        "title": "YouTube Clone",
        "desc": "Build a simplified YouTube clone with video playback and user interactions.",
        "brief": "Create a React app with video API integration, search, and likes/comments features. Submit a hosted link or code repository.",
        "karma": 600,
        "hashtag": "#cl-youtubeclone",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdVideoLibrary />",
        "skills": ["React Components", "API Integration", "State Management"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 12:30 PM",
        "prerequisites": ["Intermediate JavaScript", "Basic React"],
        "resources": ["https://reactjs.org/"]
      },
      {
        "id": "6-2",
        "title": "Portfolio Website",
        "desc": "Create a personal portfolio with dynamic content and navigation.",
        "brief": "Build a React portfolio site with multiple sections and routing. Submit a hosted link or code repository.",
        "karma": 500,
        "hashtag": "#cl-portfolio",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdPerson />",
        "skills": ["React Routing", "Component Composition", "Responsive Design"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 12:40 PM",
        "prerequisites": ["Intermediate JavaScript", "Basic React"],
        "resources": ["https://reactrouter.com/"]
      },
      {
        "id": "6-3",
        "title": "Movie App",
        "desc": "Develop a movie app with search and watchlist features.",
        "brief": "Create a React app using a movie API (e.g., TMDB) with pagination or infinite scroll. Submit a hosted link or code repository.",
        "karma": 600,
        "hashtag": "#cl-movieapp",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdMovie />",
        "skills": ["React Hooks", "API Fetching", "Infinite Scroll"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 12:50 PM",
        "prerequisites": ["Intermediate JavaScript", "Basic React"],
        "resources": ["https://www.themoviedb.org/documentation/api"]
      },
      {
        "id": "6-4",
        "title": "Budget App",
        "desc": "Build a budget tracker with analytics and data persistence.",
        "brief": "Create a React app for income/expense tracking with charts (e.g., Chart.js). Submit a hosted link or code repository.",
        "karma": 550,
        "hashtag": "#cl-budgetapp",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdAttachMoney />",
        "skills": ["React State", "Data Visualization", "Local Storage"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 1:00 PM",
        "prerequisites": ["Intermediate JavaScript", "Basic React"],
        "resources": ["https://reactjs.org/docs/hooks-intro.html"]
      },
      {
        "id": "6-5",
        "title": "Chat Application",
        "desc": "Develop a real-time chat app with authentication.",
        "brief": "Build a React app with Firebase for real-time messaging and auth. Submit a hosted link or code repository.",
        "karma": 650,
        "hashtag": "#cl-chatapp",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdChat />",
        "skills": ["React Hooks", "Real-time Data", "Authentication"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 1:10 PM",
        "prerequisites": ["Intermediate JavaScript", "Basic React"],
        "resources": ["https://firebase.google.com/docs"]
      },
      {
        "id": "6-6",
        "title": "Todo List",
        "desc": "Create a task management app with local storage.",
        "brief": "Build a React todo list with CRUD operations and filtering. Submit a hosted link or code repository.",
        "karma": 400,
        "hashtag": "#cl-todolist",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdChecklist />",
        "skills": ["React Components", "State Management", "Local Storage"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 1:20 PM",
        "prerequisites": ["Intermediate JavaScript", "Basic React"],
        "resources": ["https://reactjs.org/docs/getting-started.html"]
      },
      {
        "id": "6-7",
        "title": "Real-Time Chat Application",
        "desc": "Build a real-time chat app with Angular and WebSockets.",
        "brief": "Create an Angular app with Socket.io, Node.js, and Firebase/MongoDB. Submit a hosted link or code repository.",
        "karma": 700,
        "hashtag": "#cl-angularchat",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdChat />",
        "skills": ["Angular Components", "WebSockets", "Authentication"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 1:30 PM",
        "prerequisites": ["Intermediate JavaScript", "Basic Angular"],
        "resources": ["https://angular.io/", "https://socket.io/"]
      },
      {
        "id": "6-8",
        "title": "E-Commerce Dashboard",
        "desc": "Develop an e-commerce dashboard with CRUD and filtering.",
        "brief": "Build an Angular app with REST API integration and NgRx. Submit a hosted link or code repository.",
        "karma": 750,
        "hashtag": "#cl-ecommercedash",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdShoppingCart />",
        "skills": ["Angular Services", "RxJS", "CRUD Operations"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 1:40 PM",
        "prerequisites": ["Intermediate JavaScript", "Basic Angular"],
        "resources": ["https://angular.io/docs"]
      },
      {
        "id": "6-9",
        "title": "Common Skills Development",
        "desc": "Demonstrate Angular skills in a small project.",
        "brief": "Create a mini Angular project (e.g., dashboard) showcasing key skills. Submit a hosted link or code repository.",
        "karma": 500,
        "hashtag": "#cl-angularskills",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdDashboard />",
        "skills": ["Angular Architecture", "State Management", "API Integration"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 1:50 PM",
        "prerequisites": ["Intermediate JavaScript", "Basic Angular"],
        "resources": ["https://angular.io/guide/architecture"]
      },
      {
        "id": "6-10",
        "title": "Weather Dashboard with Svelte",
        "desc": "Build a responsive weather dashboard using Svelte.",
        "brief": "Create a Svelte app with OpenWeatherMap API integration. Submit a hosted GitHub repository with #cl-svelte-weather.",
        "karma": 600,
        "hashtag": "#cl-svelte-weather",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdWbSunny />",
        "skills": ["Svelte Components", "API Integration", "Reactivity"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 2:00 PM",
        "prerequisites": ["Intermediate JavaScript", "Basic Svelte"],
        "resources": ["https://svelte.dev/", "https://openweathermap.org/api"]
      },
      {
        "id": "6-11",
        "title": "To-Do List Application with Svelte",
        "desc": "Develop a to-do list app with persistent storage using Svelte.",
        "brief": "Build a Svelte todo app with Svelte Stores and LocalStorage. Submit a hosted GitHub repository with #cl-svelte-todo.",
        "karma": 500,
        "hashtag": "#cl-svelte-todo",
        "discordChannelName": "web-dev",
        "ig": "Web Development",
        "icon": "<MdChecklist />",
        "skills": ["Svelte Stores", "Reactivity", "Local Storage"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 2:10 PM",
        "prerequisites": ["Intermediate JavaScript", "Basic Svelte"],
        "resources": ["https://svelte.dev/docs"]
      }
    ]
  }
];