export const levelsDataCybersecurity = [
    {
      "level": 4,
      "title": "Level 4",
      "subtitle": "Fundamental IT Skills for Cybersecurity",
      "cards": [
        {
          "id": "4-1",
          "title": "TryHackMe Introduction",
          "desc": "Complete introductory TryHackMe rooms to get started with cybersecurity basics.",
          "brief": "Complete the 'Hello' and 'OpenVPN' rooms on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 20,
          "hashtag": "#cl-cybersec-thmhello",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdLock />",
          "skills": ["TryHackMe Basics", "VPN Setup", "Platform Navigation"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 10:00 AM",
          "prerequisites": ["Basic computer skills"],
          "resources": [
            "https://tryhackme.com/room/hello",
            "https://tryhackme.com/room/openvpn"
          ]
        },
        {
          "id": "4-2",
          "title": "Principles of Security",
          "desc": "Understand core security principles through TryHackMe's guided tasks.",
          "brief": "Complete the 'Principles of Security' room on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 50,
          "hashtag": "#cl-cybersec-principlesofsecurity",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdShield />",
          "skills": ["CIA Triad", "Security Concepts", "Risk Management"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 10:10 AM",
          "prerequisites": ["Basic cybersecurity interest"],
          "resources": ["https://tryhackme.com/room/principlesofsecurity"]
        },
        {
          "id": "4-3",
          "title": "Write a Blog",
          "desc": "Share insights on hacking, virtual machines, Linux, and networking in a blog.",
          "brief": "Write a 500-word blog on hacking, VMs, Linux, and networking. Submit the public blog URL.",
          "karma": 100,
          "hashtag": "#cl-cybersec-bloghackingintro",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdCreate />",
          "skills": ["Technical Writing", "Networking Basics", "Linux Basics"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 10:20 AM",
          "prerequisites": ["Basic IT knowledge"],
          "resources": ["https://medium.com/"]
        },
        {
          "id": "4-4",
          "title": "Introduction to Offensive Security",
          "desc": "Learn offensive security concepts through TryHackMe's guided tasks.",
          "brief": "Complete the 'Introduction to Offensive Security' room on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 20,
          "hashtag": "#cl-cybersec-thmintrotooffensivesecurity",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdAttack />",
          "skills": ["Penetration Testing Basics", "Ethical Hacking", "Offensive Techniques"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 10:30 AM",
          "prerequisites": ["Basic cybersecurity knowledge"],
          "resources": ["https://tryhackme.com/room/introtooffensivesecurity"]
        },
        {
          "id": "4-5",
          "title": "Cisco Networking Basics",
          "desc": "Earn a Cisco badge by mastering networking fundamentals.",
          "brief": "Complete the 'Networking Basics' course on SkillsForAll and submit your badge.",
          "karma": 800,
          "hashtag": "#cl-cybersec-cisconetworkingbasics",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdNetworkCheck />",
          "skills": ["Networking Fundamentals", "Cisco Tools", "Protocol Basics"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 10:40 AM",
          "prerequisites": ["Basic IT skills"],
          "resources": [
            "https://skillsforall.com/course/networking-basics?courseLang=en-US"
          ]
        },
        {
          "id": "4-6",
          "title": "IoT PenTesting",
          "desc": "Demonstrate IoT pentesting skills through TryHackMe tasks.",
          "brief": "Complete the 'IoT Pentesting' room on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 20,
          "hashtag": "#cl-cybersec-thmintroiotpentesting",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdDevicesOther />",
          "skills": ["IoT Pentesting", "Vulnerability Identification", "TryHackMe"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 10:50 AM",
          "prerequisites": ["Basic networking knowledge"],
          "resources": ["https://tryhackme.com/room/iotintro"]
        },
        {
          "id": "4-7",
          "title": "Cisco Packet Tracer",
          "desc": "Earn badges by completing Cisco Packet Tracer courses.",
          "brief": "Complete four SkillsForAll Packet Tracer courses and submit your badges.",
          "karma": 1200,
          "hashtag": "#cl-cybersec-ciscopackettracer",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdRouter />",
          "skills": ["Packet Tracer", "Networking Simulation", "IoT Basics"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 11:00 AM",
          "prerequisites": ["Basic networking knowledge"],
          "resources": [
            "https://skillsforall.com/exam/introduction-packet-tracer?courseLang=en-US",
            "https://skillsforall.com/course/getting-started-cisco-packet-tracer?courseLang=en-US",
            "https://skillsforall.com/course/exploring-networking-cisco-packet-tracer?courseLang=en-US",
            "https://skillsforall.com/course/exploring-iot-cisco-packet-tracer?courseLang=en-US"
          ]
        }
      ]
    },
    {
      "level": 5,
      "title": "Level 5",
      "subtitle": "Networking and Security Tools",
      "cards": [
        {
          "id": "5-1",
          "title": "Web Application Security",
          "desc": "Master web application security concepts through TryHackMe.",
          "brief": "Complete the 'Intro to Web Application Security' room on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 20,
          "hashtag": "#cl-cybersec-thmwebapplicationsecurity",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdWeb />",
          "skills": ["Web App Security", "Vulnerability Basics", "TryHackMe"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 11:10 AM",
          "prerequisites": ["Basic cybersecurity knowledge"],
          "resources": ["https://tryhackme.com/room/introwebapplicationsecurity"]
        },
        {
          "id": "5-2",
          "title": "Nmap Mastery",
          "desc": "Demonstrate expertise in network scanning with Nmap.",
          "brief": "Complete the 'Further Nmap' room on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 200,
          "hashtag": "#cl-cybersec-thmnmap",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdSearch />",
          "skills": ["Nmap Usage", "Port Scanning", "Network Discovery"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 11:20 AM",
          "prerequisites": ["Basic networking knowledge"],
          "resources": ["https://tryhackme.com/room/furthernmap"]
        },
        {
          "id": "5-3",
          "title": "Google Dorking Proficiency",
          "desc": "Learn advanced search techniques with Google Dorking.",
          "brief": "Complete the 'Google Dorking' room on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 100,
          "hashtag": "#cl-cybersec-googledorking",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdSearch />",
          "skills": ["Google Dorking", "Open-Source Intelligence", "Search Techniques"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 11:30 AM",
          "prerequisites": ["Basic internet skills"],
          "resources": ["https://tryhackme.com/room/googledorking"]
        },
        {
          "id": "5-4",
          "title": "Threat Intelligence & Tools Mastery",
          "desc": "Gain proficiency in threat intelligence tools via TryHackMe.",
          "brief": "Complete the 'Threat Intelligence Tools' room on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 100,
          "hashtag": "#cl-cybersec-thmthreatintelligencetools",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdAnalytics />",
          "skills": ["Threat Intelligence", "Tool Usage", "Cyber Threat Analysis"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 11:40 AM",
          "prerequisites": ["Basic cybersecurity knowledge"],
          "resources": ["https://tryhackme.com/room/threatinteltools"]
        },
        {
          "id": "5-5",
          "title": "Shodan.io",
          "desc": "Learn to use Shodan.io for network exploration.",
          "brief": "Complete the 'Shodan' room on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 100,
          "hashtag": "#cl-cybersec-thmshodan",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdSearch />",
          "skills": ["Shodan Usage", "Network Reconnaissance", "OSINT"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 11:50 AM",
          "prerequisites": ["Basic networking knowledge"],
          "resources": ["https://tryhackme.com/room/shodan"]
        },
        {
          "id": "5-6",
          "title": "Burp Suite Mastery",
          "desc": "Master web security testing with Burp Suite.",
          "brief": "Complete the 'Burp Suite Basics' and 'Burp Suite Repeater' rooms on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 400,
          "hashtag": "#cl-cybersec-burpsuite",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdBugReport />",
          "skills": ["Burp Suite", "Web Vulnerability Testing", "Proxy Tools"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 12:00 PM",
          "prerequisites": ["Basic web security knowledge"],
          "resources": [
            "https://tryhackme.com/room/burpsuitebasics",
            "https://tryhackme.com/room/burpsuiterepeater"
          ]
        },
        {
          "id": "5-7",
          "title": "Nessus",
          "desc": "Learn vulnerability scanning with Nessus.",
          "brief": "Complete the 'RP: Nessus Redux' room on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 100,
          "hashtag": "#cl-cybersec-thmnessus",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdScanner />",
          "skills": ["Nessus Usage", "Vulnerability Assessment", "Scanning Tools"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 12:10 PM",
          "prerequisites": ["Basic cybersecurity knowledge"],
          "resources": ["https://tryhackme.com/room/rpnessusredux"]
        },
        {
          "id": "5-8",
          "title": "SQLMap",
          "desc": "Master SQL injection testing with SQLMap.",
          "brief": "Complete the 'SQLMap' room on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 100,
          "hashtag": "#cl-cybersec-sqlmap",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdCode />",
          "skills": ["SQLMap Usage", "SQL Injection", "Pentesting Tools"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 12:20 PM",
          "prerequisites": ["Basic web security knowledge"],
          "resources": ["https://tryhackme.com/room/sqlmap"]
        },
        {
          "id": "5-9",
          "title": "Hydra Proficiency",
          "desc": "Learn password cracking with Hydra.",
          "brief": "Complete the 'Hydra' room on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 50,
          "hashtag": "#cl-cybersec-thmhydra",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdKey />",
          "skills": ["Hydra Usage", "Brute Force Attacks", "Pentesting"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 12:30 PM",
          "prerequisites": ["Basic cybersecurity knowledge"],
          "resources": ["https://tryhackme.com/room/hydra"]
        },
        {
          "id": "5-10",
          "title": "Metasploit Introduction",
          "desc": "Get started with Metasploit for penetration testing.",
          "brief": "Complete the 'Metasploit Intro' room on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 50,
          "hashtag": "#cl-cybersec-thmmetasploit",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdBugReport />",
          "skills": ["Metasploit Basics", "Exploitation", "Pentesting"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 12:40 PM",
          "prerequisites": ["Basic cybersecurity knowledge"],
          "resources": ["https://tryhackme.com/room/metasploitintro"]
        },
        {
          "id": "5-11",
          "title": "Digital Forensics Introduction",
          "desc": "Learn the basics of digital forensics.",
          "brief": "Complete the 'Intro to Digital Forensics' room on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 50,
          "hashtag": "#cl-cybersec-thmintrodigitalforensics",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdFingerprint />",
          "skills": ["Forensics Basics", "Evidence Analysis", "TryHackMe"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 12:50 PM",
          "prerequisites": ["Basic cybersecurity knowledge"],
          "resources": ["https://tryhackme.com/room/introdigitalforensics"]
        },
        {
          "id": "5-12",
          "title": "Cryptography Introduction",
          "desc": "Understand the fundamentals of cryptography.",
          "brief": "Complete the 'Introduction to Cryptography' room on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 200,
          "hashtag": "#cl-cybersec-introcryptography",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdVpnKey />",
          "skills": ["Cryptography Basics", "Encryption", "Security Protocols"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 1:00 PM",
          "prerequisites": ["Basic IT knowledge"],
          "resources": ["https://tryhackme.com/room/cryptographyintro"]
        },
        {
          "id": "5-13",
          "title": "Malware Introductory",
          "desc": "Gain foundational knowledge about malware analysis.",
          "brief": "Complete the 'Malware Introductory' room on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 100,
          "hashtag": "#cl-cybersec-thmmalwareintroductory",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdVirus />",
          "skills": ["Malware Basics", "Threat Analysis", "TryHackMe"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 1:10 PM",
          "prerequisites": ["Basic cybersecurity knowledge"],
          "resources": ["https://tryhackme.com/room/malmalintroductory"]
        },
        {
          "id": "5-14",
          "title": "Android Hacking",
          "desc": "Learn the basics of Android hacking.",
          "brief": "Complete the 'Android Hacking 101' room on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 50,
          "hashtag": "#cl-cybersec-thmintroandroidhacking101",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdPhoneAndroid />",
          "skills": ["Android Hacking", "Mobile Pentesting", "TryHackMe"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 1:20 PM",
          "prerequisites": ["Basic cybersecurity knowledge"],
          "resources": ["https://tryhackme.com/room/androidhacking101"]
        },
        {
          "id": "5-15",
          "title": "Bash Script Port Scanning",
          "desc": "Develop a Bash script for port scanning.",
          "brief": "Write a Bash script for port scanning and upload it to GitHub. Submit the repository URL.",
          "karma": 200,
          "hashtag": "#cl-cybersec-bashscriptportscanning",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdCode />",
          "skills": ["Bash Scripting", "Port Scanning", "Automation"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 1:30 PM",
          "prerequisites": ["Basic Linux knowledge"],
          "resources": []
        }
      ]
    },
    {
      "level": 6,
      "title": "Level 6",
      "subtitle": "Advanced Cybersecurity Skills",
      "cards": [
        {
          "id": "6-1",
          "title": "DVWA Vulnerability Analysis Report",
          "desc": "Create a detailed report on exploiting DVWA vulnerabilities.",
          "brief": "Exploit all DVWA vulnerabilities and submit a PDF report following the sample format.",
          "karma": 400,
          "hashtag": "#cl-cybersec-dvwa",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdReport />",
          "skills": ["Vulnerability Exploitation", "Report Writing", "Web Security"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 1:40 PM",
          "prerequisites": ["Intermediate web security knowledge"],
          "resources": [
            "https://www.vulnhub.com/entry/damn-vulnerable-web-application-dvwa-107,43/",
            "https://cybereaon.com/wp-content/uploads/2021/05/sample_report_web.pdf"
          ]
        },
        {
          "id": "6-2",
          "title": "OWASP Juice Shop",
          "desc": "Master web app security with OWASP Juice Shop on TryHackMe.",
          "brief": "Complete the 'OWASP Juice Shop' room on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 400,
          "hashtag": "#cl-cybersec-owaspjuiceshop",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdWeb />",
          "skills": ["OWASP Vulnerabilities", "Web Pentesting", "TryHackMe"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 1:50 PM",
          "prerequisites": ["Intermediate web security knowledge"],
          "resources": ["https://tryhackme.com/room/owaspjuiceshop"]
        },
        {
          "id": "6-3",
          "title": "OWASP Top 10 Proficiency",
          "desc": "Demonstrate expertise in OWASP Top 10 vulnerabilities.",
          "brief": "Complete the 'OWASP Top 10' room on TryHackMe to 100% completion. Submit your public profile URL.",
          "karma": 800,
          "hashtag": "#cl-cybersec-owasptop10",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdSecurity />",
          "skills": ["OWASP Top 10", "Vulnerability Assessment", "Web Pentesting"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 2:00 PM",
          "prerequisites": ["Intermediate web security knowledge"],
          "resources": ["https://tryhackme.com/room/owasptop10"]
        },
        {
          "id": "6-4",
          "title": "VulnHub Web Machine Challenge",
          "desc": "Compromise a VulnHub machine and document the process.",
          "brief": "Penetrate the 'Web Machine N7' VulnHub VM and submit a PDF write-up.",
          "karma": 800,
          "hashtag": "#cl-cybersec-webmachine",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdBugReport />",
          "skills": ["Penetration Testing", "Vulnerability Exploitation", "Report Writing"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 2:10 PM",
          "prerequisites": ["Advanced cybersecurity knowledge"],
          "resources": ["https://www.vulnhub.com/entry/web-machine-n7,756/"]
        },
        {
          "id": "6-5",
          "title": "VulnHub WebSploit Challenge",
          "desc": "Exploit vulnerabilities in a VulnHub WebSploit machine.",
          "brief": "Penetrate the 'WebSploit 2018' VulnHub VM and submit a PDF write-up.",
          "karma": 800,
          "hashtag": "#cl-cybersec-websploit",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdBugReport />",
          "skills": ["Penetration Testing", "Web Exploitation", "Report Writing"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 2:20 PM",
          "prerequisites": ["Advanced cybersecurity knowledge"],
          "resources": ["https://www.vulnhub.com/entry/websploit2018-1,253/"]
        },
        {
          "id": "6-6",
          "title": "VulnHub OWASP Broken Web Application Challenge",
          "desc": "Hack the OWASP Broken Web Apps VulnHub machine.",
          "brief": "Penetrate the 'OWASP Broken Web Apps' VulnHub VM and submit a PDF write-up.",
          "karma": 800,
          "hashtag": "#cl-cybersec-owaspbrokenwebapp",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdBugReport />",
          "skills": ["Web Pentesting", "Vulnerability Exploitation", "Report Writing"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 2:30 PM",
          "prerequisites": ["Advanced web security knowledge"],
          "resources": ["https://www.vulnhub.com/entry/owasp-broken-web-applications-project-12,46/"]
        },
        {
          "id": "6-7",
          "title": "CSRF Vulnerability Crawler and Research",
          "desc": "Research CSRF protections and build a crawler for vulnerabilities.",
          "brief": "Research CSRF, create a crawler and PoC HTML form, and upload to GitHub. Submit the repository URL.",
          "karma": 800,
          "hashtag": "#cl-cybersec-crawler",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdWeb />",
          "skills": ["CSRF Research", "Web Crawling", "PoC Development"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 2:40 PM",
          "prerequisites": ["Advanced web security and scripting knowledge"],
          "resources": []
        },
        {
          "id": "6-8",
          "title": "WAF Evasion for XSS - Python Script",
          "desc": "Develop a Python script to evade WAF filters for XSS attacks.",
          "brief": "Research WAFs, create an XSS evasion script in Python, and upload to GitHub with documentation. Submit the repository URL.",
          "karma": 800,
          "hashtag": "#cl-cybersec-pysxss",
          "discordChannelName": "cyber-security",
          "ig": "Cyber Security",
          "icon": "<MdCode />",
          "skills": ["WAF Evasion", "Python Scripting", "XSS Exploitation"],
          "publishedBy": "Community",
          "publishedWhen": "2/26/25, 2:50 PM",
          "prerequisites": ["Advanced web security and Python knowledge"],
          "resources": []
        }
      ]
    }
  ];