export const levelsDataUIUX = [
  {
    "level": 4,
    "title": "Level 4",
    "subtitle": "Master UI/UX Fundamentals",
    "cards": [
      {
        "id": "4-1",
        "title": "Find and Define a Simple Problem",
        "desc": "Prepare a problem statement based on research, user needs, and business goals, and design a solution that meets those needs.",
        "brief": "Define a simple problem addressing What, Why, When, Who, and Where. Submit a PDF or Word file with your problem statement and solution.",
        "karma": 100,
        "hashtag": "#cl-findaproblem",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdSearch />",
        "skills": ["Problem Definition", "User Research", "Solution Design"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 10:00 AM",
        "prerequisites": ["Basic understanding of user needs"],
        "resources": [
          "https://drive.google.com/file/d/17WuscJPIhgaq0VOnyi2wOTRfpZSpc16-/view",
          "https://www.coursera.org/lecture/start-ux-design-process/create-problem-statements-NC282"
        ]
      },
      {
        "id": "4-2",
        "title": "Figma Basics",
        "desc": "Learn Figma basics by cloning three screens of your favorite app.",
        "brief": "Clone a home screen and two other screens of an app in Figma. Submit your Figma file.",
        "karma": 400,
        "hashtag": "#cl-ui-figma",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdBrush />",
        "skills": ["Figma Basics", "UI Cloning", "Screen Design"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 10:10 AM",
        "prerequisites": ["Basic design curiosity"],
        "resources": [
          "https://www.classcentral.com/classroom/youtube-figma-tutorials-the-ultimate-crash-course-51794"
        ]
      },
      {
        "id": "4-3",
        "title": "Sun and Moon",
        "desc": "Create toggle buttons inspired by a tutorial video.",
        "brief": "Watch the provided video and design your own toggle buttons in Figma. Submit your Figma file.",
        "karma": 400,
        "hashtag": "#cl-ui-sunmoon",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdToggleOn />",
        "skills": ["Figma Design", "Button Design", "Interaction Basics"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 10:20 AM",
        "prerequisites": ["Basic Figma knowledge"],
        "resources": ["https://www.youtube.com/watch?v=rKtBy63cHJ4"]
      },
      {
        "id": "4-4",
        "title": "Create a User Persona",
        "desc": "Create personas for three target users based on research and data.",
        "brief": "Design personas including demographics, needs, goals, pain points, and quotes. Submit a PDF or Word file.",
        "karma": 400,
        "hashtag": "#cl-ux-persona",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdPerson />",
        "skills": ["User Research", "Persona Creation", "Empathy Mapping"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 10:30 AM",
        "prerequisites": ["Basic understanding of user research"],
        "resources": [
          "https://www.coursera.org/lecture/start-ux-design-process/understand-personas-ZpYoj"
        ]
      },
      {
        "id": "4-5",
        "title": "Create a User Journey Map",
        "desc": "Visually illustrate a user flow from initial contact to long-term loyalty.",
        "brief": "Design a user journey map with stages of engagement using the provided template. Submit a PDF or Word file.",
        "karma": 600,
        "hashtag": "#cl-ux-journeymap",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdMap />",
        "skills": ["User Flow", "Journey Mapping", "Visualization"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 10:40 AM",
        "prerequisites": ["Basic UX concepts"],
        "resources": [
          "https://www.figma.com/board/M8m8Dn0cTEPVaVZoqXpGy6/Journey-map?node-id=0-1&p=f&t=yea1zM3YfAF7kHGB-0"
        ]
      },
      {
        "id": "4-6",
        "title": "Create Simple Wireframes",
        "desc": "Learn to create wireframes showing layout, elements, and user flow.",
        "brief": "Design wireframes with at least 4 windows in Figma. Submit your Figma file link with edit access.",
        "karma": 400,
        "hashtag": "#cl-ux-wireframe",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdDevices />",
        "skills": ["Wireframing", "User Flow", "Figma Basics"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 10:50 AM",
        "prerequisites": ["Basic Figma knowledge"],
        "resources": [
          "https://www.coursera.org/lecture/wireframes-low-fidelity-prototypes/draw-your-first-wireframe-wN5Wk"
        ]
      },
      {
        "id": "4-7",
        "title": "Analyze a Website for UX Issues",
        "desc": "Analyze a website to identify UX issues and provide recommendations.",
        "brief": "Review a website for navigation, accessibility, and performance issues. Submit a PDF or Word file (min 4 pages) with findings and recommendations.",
        "karma": 300,
        "hashtag": "#cl-ux-uxissues",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdWeb />",
        "skills": ["UX Evaluation", "Problem Identification", "Documentation"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 11:00 AM",
        "prerequisites": ["Basic UX knowledge"],
        "resources": ["https://www.youtube.com/watch?v=GXTkczM8nmY"]
      },
      {
        "id": "4-8",
        "title": "Basics of User-Centered Design",
        "desc": "Explore User-Centered Design principles and apply them to a mobile app example.",
        "brief": "Document the UCD process (research, ideation, prototyping, testing, iteration) for a mobile app. Submit a PDF.",
        "karma": 300,
        "hashtag": "#cl-ux-ucd",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdPeople />",
        "skills": ["User-Centered Design", "Iterative Process", "Documentation"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 11:10 AM",
        "prerequisites": ["Basic design principles"],
        "resources": ["https://youtu.be/BTVLmf0Z6EY?si=ROUHeSp5LmSX9VmT"]
      },
      {
        "id": "4-9",
        "title": "Introduction to Prototyping",
        "desc": "Learn prototyping basics and design a simple user flow.",
        "brief": "Design and test a prototype (e.g., login to dashboard) in Figma. Submit a PDF documenting the process.",
        "karma": 300,
        "hashtag": "#cl-ux-prototype",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdSmartphone />",
        "skills": ["Prototyping", "User Flow", "Figma Basics"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 11:20 AM",
        "prerequisites": ["Basic Figma knowledge"],
        "resources": ["https://youtu.be/v1UKB-0EUhQ?si=teHsvMDhz23uXurJ"]
      },
      {
        "id": "4-10",
        "title": "Low-Fidelity UI Designs",
        "desc": "Create a low-fidelity prototype focusing on function over appearance.",
        "brief": "Design a low-fi prototype with at least 8 windows in Figma. Submit your Figma file URL.",
        "karma": 400,
        "hashtag": "#cl-ux-lowfi",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdOutlineDesignServices />",
        "skills": ["Low-Fidelity Prototyping", "Figma Design", "User Flow"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 11:30 AM",
        "prerequisites": ["Basic Figma and wireframing knowledge"],
        "resources": ["https://www.youtube.com/watch?v=3F4mWr1cY-8"]
      }
    ]
  },
  {
    "level": 5,
    "title": "Level 5",
    "subtitle": "Develop Intermediate UI/UX Skills",
    "cards": [
      {
        "id": "5-1",
        "title": "Create a Competitive Audit Report",
        "desc": "Assess a company’s competitors, highlighting strengths, weaknesses, and opportunities.",
        "brief": "Analyze at least 3 competitors and provide recommendations in a PDF report using the provided template.",
        "karma": 800,
        "hashtag": "#cl-ux-competitivereport",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdAssessment />",
        "skills": ["Competitive Analysis", "Report Writing", "Strategic Thinking"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 11:40 AM",
        "prerequisites": ["Basic UX research skills"],
        "resources": [
          "https://www.coursera.org/lecture/start-ux-design-process/steps-to-conduct-a-competitive-audit-JG2nZ",
          "https://www.figma.com/file/BhVVDrtphX5VSCqTz1wPaR/Competitor-Analysis-(Copy)?type=whiteboard&node-id=0%3A1&t=k2lljhoo7M05lcxm-1"
        ]
      },
      {
        "id": "5-2",
        "title": "Card Sorting Design Method",
        "desc": "Learn card sorting to organize website content into user-friendly categories.",
        "brief": "Sort at least 12 cards and submit a PDF or image of the cards plus a report on findings.",
        "karma": 800,
        "hashtag": "#cl-ux-cardsorting",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdSort />",
        "skills": ["Card Sorting", "Content Organization", "User Research"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 11:50 AM",
        "prerequisites": ["Basic UX and IA knowledge"],
        "resources": ["https://youtu.be/AxgMIEVcIMY?si=rw3aqxuneXr0uVPp"]
      },
      {
        "id": "5-3",
        "title": "Understanding Breakpoints and Grid",
        "desc": "Learn breakpoints and grid systems for responsive design.",
        "brief": "Design a webpage layout in Figma with a grid system and breakpoints for mobile, tablet, and desktop. Submit your Figma file URL.",
        "karma": 800,
        "hashtag": "#cl-ux-brakpointsandgrid",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdGridOn />",
        "skills": ["Responsive Design", "Grid Systems", "Breakpoints"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 12:00 PM",
        "prerequisites": ["Intermediate Figma knowledge"],
        "resources": [
          "https://youtu.be/c0ZTaDMGb20?si=aPDomzhBJV1jcC9M",
          "https://youtu.be/gHdcAH1nhiU?si=YBpZfcCqRG7lxzEt"
        ]
      },
      {
        "id": "5-4",
        "title": "Create Responsive Component",
        "desc": "Design a responsive UI component adaptable to various screen sizes.",
        "brief": "Choose a component (e.g., nav bar, card) and design it in Figma for mobile, tablet, and desktop. Submit your Figma file URL.",
        "karma": 400,
        "hashtag": "#cl-ux-responsivecomponent",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdDevices />",
        "skills": ["Responsive Design", "Component Design", "Figma"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 12:10 PM",
        "prerequisites": ["Intermediate Figma knowledge"],
        "resources": ["https://youtu.be/oXDAmwEWlDc?si=psRxny5y7tfvM0ud"]
      },
      {
        "id": "5-5",
        "title": "Interactive Multi-Step Form",
        "desc": "Design an interactive multi-step form to improve user experience.",
        "brief": "Create a multi-step form prototype in Figma with validation and progress indicators. Submit Figma file and prototype URLs.",
        "karma": 400,
        "hashtag": "#cl-ux-form",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdInput />",
        "skills": ["Form Design", "Prototyping", "Interactivity"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 12:20 PM",
        "prerequisites": ["Intermediate Figma and prototyping skills"],
        "resources": ["https://youtu.be/iiHDu_Ko6Xg?si=2GuHrTnDQxiQVLVI"]
      },
      {
        "id": "5-6",
        "title": "Design an Onboarding Flow",
        "desc": "Redesign the MuLearn onboarding flow for clarity and ease of use.",
        "brief": "Analyze MuLearn’s onboarding, design a simplified flow, and create an interactive prototype in Figma. Submit Figma file and prototype URLs.",
        "karma": 600,
        "hashtag": "#cl-ux-onboarding",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdDirections />",
        "skills": ["Onboarding Design", "User Flow", "Prototyping"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 12:30 PM",
        "prerequisites": ["Intermediate UX and Figma skills"],
        "resources": ["https://mulearn.org/"]
      },
      {
        "id": "5-7",
        "title": "Design a Splash Screen",
        "desc": "Create a visually appealing splash screen reflecting brand identity.",
        "brief": "Design a responsive splash screen in Figma with an interactive prototype. Submit Figma file and prototype URLs.",
        "karma": 600,
        "hashtag": "#cl-ux-splashscreen",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdBrush />",
        "skills": ["Visual Design", "Branding", "Prototyping"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 12:40 PM",
        "prerequisites": ["Intermediate Figma and UI skills"],
        "resources": ["https://youtu.be/CZ440x65k-g?si=So63AmMoVHh3mjYI"]
      }
    ]
  },
  {
    "level": 6,
    "title": "Level 6",
    "subtitle": "Master Core UI/UX Skills",
    "cards": [
      {
        "id": "6-1",
        "title": "Create an Information Architecture",
        "desc": "Structure and organize digital content for enhanced navigation.",
        "brief": "Design an IA with hierarchies and navigation systems (min 4 pages). Submit a PDF or image with a report.",
        "karma": 800,
        "hashtag": "#cl-ux-infoarch",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdLayers />",
        "skills": ["Information Architecture", "Content Organization", "Navigation Design"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 12:50 PM",
        "prerequisites": ["Intermediate UX and IA knowledge"],
        "resources": ["https://youtu.be/Ij4WquJaRTc?si=YaiwZn0Hos7EbfAo"]
      },
      {
        "id": "6-2",
        "title": "Create a Navigation Bar",
        "desc": "Design a clean, user-friendly navigation bar for desktop and mobile.",
        "brief": "Design a responsive navigation bar with an interactive prototype in Figma. Submit Figma file and prototype URLs.",
        "karma": 400,
        "hashtag": "#cl-ux-navigationbar",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdMenu />",
        "skills": ["Navigation Design", "Responsive Design", "Prototyping"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 1:00 PM",
        "prerequisites": ["Intermediate Figma and UI skills"],
        "resources": ["https://youtu.be/Ox7uNtdHC8w?si=qto3i0d0n_CXCp30"]
      },
      {
        "id": "6-3",
        "title": "Create a Slider",
        "desc": "Design a responsive slider with navigation elements and transitions.",
        "brief": "Create a slider prototype in Figma for desktop and mobile. Submit Figma file and prototype URLs.",
        "karma": 200,
        "hashtag": "#cl-ux-slider",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdSlideshow />",
        "skills": ["Slider Design", "Responsive Design", "Prototyping"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 1:10 PM",
        "prerequisites": ["Intermediate Figma and interaction skills"],
        "resources": ["https://youtu.be/2d32vTtJUnw?si=CCIuegdMb2dciQWQ"]
      },
      {
        "id": "6-4",
        "title": "Create a Responsive and Interactive Accordion in Figma",
        "desc": "Design a responsive accordion layout with interactive elements.",
        "brief": "Create an accordion prototype in Figma with collapsible panels for multiple devices. Submit Figma file and prototype URLs.",
        "karma": 500,
        "hashtag": "#cl-ux-accordion",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdExpandMore />",
        "skills": ["Accordion Design", "Interactivity", "Responsive Design"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 1:20 PM",
        "prerequisites": ["Intermediate Figma and prototyping skills"],
        "resources": ["https://youtu.be/SQWMFFhBSaE?si=mUDOGxJ6vS-0qtjw"]
      },
      {
        "id": "6-5",
        "title": "Hi-Fidelity UI Designs",
        "desc": "Create high-fidelity designs with interactive components and responsiveness.",
        "brief": "Design a hi-fi prototype from wireframes in Figma, including visual elements and interactivity. Submit Figma file and prototype URLs.",
        "karma": 950,
        "hashtag": "#cl-ux-hifi",
        "discordChannelName": "ui-ux",
        "ig": "UIUX",
        "icon": "<MdDesignServices />",
        "skills": ["High-Fidelity Design", "Visual Design", "Prototyping"],
        "publishedBy": "Community",
        "publishedWhen": "2/26/25, 1:30 PM",
        "prerequisites": ["Advanced Figma and UI/UX skills"],
        "resources": ["https://youtu.be/Fr-f2NE6B3U?si=NbmPO5EY8AlS1Nsa"]
      }
    ]
  }
];