import React from "react";
import {
  MdSchool,
  MdLightbulb,
  MdSensors,
  MdDevices,
  MdWaves,
  MdWater,
  MdLightMode,
  MdRadar,
  MdSettingsRemote,
  MdMonitor,
  MdHome,
  MdSecurity,
} from "react-icons/md";

const levelsDataIOT = [
  {
    level: 4,
    title: "Level 4",
    subtitle: "Internet of Things Fundamentals",
    leveller: {
      id: "4-1",
      title: "What is IoT - Greatlearning",
      desc: "In this course you'll get a basic understanding on what's IoT?\n\n🔗 https://www.mygreatlearning.com/academy/learn-for-free/courses/what-is-iot\n\nAfter course completion, share the certificate in ⁠internet-of-things-iot-and-robo… channel with hashtag **#ge-what-is-iot** to avail ⭐ 50 karma points.",
      brief:
        "Learn the fundamentals of IoT including its architecture, applications, and importance in today's connected world.",
      ig: "IoT",
      icon: <MdSchool />,
      skills: ["IoT Fundamentals", "Connected Devices", "Industry Knowledge"],
      publishedBy: "Community",
      publishedWhen: "30/12/2023, 23:58",
      prerequisites: ["None"],
      resources: [
        "https://www.mygreatlearning.com/academy/learn-for-free/courses/what-is-iot",
      ],
      hashtag: "#ge-what-is-iot",
    },
    cards: [
      {
        id: "4-1",
        title: "What is IoT - Greatlearning",
        desc: "In this course you'll get a basic understanding on what's IoT?\n\n🔗 https://www.mygreatlearning.com/academy/learn-for-free/courses/what-is-iot\n\nAfter course completion, share the certificate in ⁠internet-of-things-iot-and-robo… channel with hashtag **#ge-what-is-iot** to avail ⭐ 50 karma points.",
        brief:
          "Learn the fundamentals of IoT including its architecture, applications, and importance in today's connected world.",
        ig: "IoT",
        icon: <MdSchool />,
        skills: ["IoT Fundamentals", "Connected Devices", "Industry Knowledge"],
        publishedBy: "Community",
        publishedWhen: "30/12/2023, 23:58",
        prerequisites: ["None"],
        resources: [
          "https://www.mygreatlearning.com/academy/learn-for-free/courses/what-is-iot",
        ],
        hashtag: "#ge-what-is-iot",
      },
      {
        id: "4-2",
        title: "Cisco- Introduction to IoT",
        desc: "In this task, you are required to complete the course provided below, introducing you to IoT and how it's enabling digital transformations across a variety of industries and expanding career opportunities in the future.\n\n🔗 Check out: https://skillsforall.com/course/introduction-iot?courseLang=en-US\n\nAfter completing this task, share the certificate of course completion in the ⁠internet-of-things-iot-and-robo… channel using the hashtag **#cl-iot-cisco** to avail ⭐⭐⭐ 800 karma points.",
        brief:
          "Explore how IoT is transforming industries and creating new career opportunities through this comprehensive Cisco course.",
        ig: "IoT",
        icon: <MdLightbulb />,
        skills: ["Digital Transformation", "IoT Applications", "Industry 4.0"],
        publishedBy: "Community",
        publishedWhen: "08/01/2024, 02:47",
        prerequisites: ["Basic Technical Knowledge"],
        resources: [
          "https://skillsforall.com/course/introduction-iot?courseLang=en-US",
        ],
        hashtag: "#cl-iot-cisco",
      },
      {
        id: "4-3",
        title: "LED Blinking",
        desc: "In this task, you are required to create a code in the Wowki online simulator that controls a simple LED bulb.\n\n🔗 Check out: https://www.youtube.com/watch?v=c5btoce--ZU\n\nAfter completing this task, share the project URL in the ⁠internet-of-things-iot-and-robo… channel using the hashtag **#cl-iot-ledblinking** to avail ⭐ 50 karma points.",
        brief:
          "Create your first Arduino project by controlling an LED light in the Wokwi simulator.",
        ig: "IoT",
        icon: <MdDevices />,
        skills: ["Arduino Programming", "Basic Electronics", "Circuit Design"],
        publishedBy: "Community",
        publishedWhen: "08/01/2024, 03:04",
        prerequisites: ["Basic Programming"],
        resources: ["https://www.youtube.com/watch?v=c5btoce--ZU"],
        hashtag: "#cl-iot-ledblinking",
      },
      {
        id: "4-4",
        title: "Distance Measurement",
        desc: "In this task, you have to create a simple distance meter using ultrasonic sensors using Arduino in Wowki simulator.\n\n🔗 Check out: https://www.youtube.com/watch?v=0Lhgd8PQmn0\n\nAfter completing this task, share the project URL in the ⁠internet-of-things-iot-and-robo… channel using the hashtag **#cl-iot-distance-meter** to avail ⭐ 50 karma points.",
        brief:
          "Build a distance measuring system with Arduino and ultrasonic sensors in the Wokwi simulator.",
        ig: "IoT",
        icon: <MdWaves />,
        skills: ["Sensor Integration", "Distance Sensing", "Arduino Coding"],
        publishedBy: "Community",
        publishedWhen: "11/01/2024, 03:02",
        prerequisites: ["Basic Arduino Knowledge"],
        resources: ["https://www.youtube.com/watch?v=0Lhgd8PQmn0"],
        hashtag: "#cl-iot-distance-meter",
      },
      {
        id: "4-5",
        title: "Humidity Monitoring",
        desc: "In this task, you will have to create a humidity detector using the humidity sensor using Arduino by checking and keeping track of the temperature, in the Wowki simulator.\n\n🔗 Check out: https://www.youtube.com/watch?v=dJJAQxyryoQ\n\nAfter completing this task, share the project URL in the ⁠internet-of-things-iot-and-robo… channel using the hashtag **#cl-iot-humidity-monitor** to avail ⭐ 50 karma points.",
        brief:
          "Create an environmental monitoring system that tracks humidity and temperature with Arduino.",
        ig: "IoT",
        icon: <MdWater />,
        skills: ["Environmental Sensing", "DHT11 Sensors", "Data Monitoring"],
        publishedBy: "Community",
        publishedWhen: "11/01/2024, 03:26",
        prerequisites: ["Basic Arduino Knowledge"],
        resources: ["https://www.youtube.com/watch?v=dJJAQxyryoQ"],
        hashtag: "#cl-iot-humidity-monitor",
      },
      {
        id: "4-6",
        title: "Light Intensity Measurement",
        desc: "In this task, you have to create a light-intensity meter that detects and reacts to the change in light conditions using Arduino with the help of an LDR (Light-Dependent Resistor) sensor, in the Wowki simulator.\n\n🔗 Check out: https://www.youtube.com/watch?v=pzJvd0Rfa_c\n\nAfter completing this task, share the project URL in the ⁠internet-of-things-iot-and-robo… channel using the hashtag **#cl-iot-lightintensitymeasurement** to avail ⭐ 50 karma points.",
        brief:
          "Build a light detection system using an LDR sensor and Arduino to measure ambient light levels.",
        ig: "IoT",
        icon: <MdLightMode />,
        skills: ["Light Sensing", "Analog Sensors", "Ambient Detection"],
        publishedBy: "Community",
        publishedWhen: "11/01/2024, 03:38",
        prerequisites: ["Basic Arduino Knowledge"],
        resources: ["https://www.youtube.com/watch?v=pzJvd0Rfa_c"],
        hashtag: "#cl-iot-lightintensitymeasurement",
      },
      {
        id: "4-7",
        title: "Motion Detection Sensor",
        desc: "In this task, you are required to build a motion-activated device that detects motion with the help of a PIR (Passive Infrared) sensor using Arduino in the Wowki simulator.\n\n🔗 Check out: https://www.youtube.com/watch?v=hNmacZoweqY\n\nAfter completing this task, share the project URL in the ⁠internet-of-things-iot-and-robo… channel using the hashtag **#cl-iot-motiondetector** to avail ⭐ 50 karma points.",
        brief:
          "Create a motion detection system using PIR sensors and Arduino to identify movement in a space.",
        ig: "IoT",
        icon: <MdRadar />,
        skills: ["Motion Detection", "PIR Sensors", "Event Triggering"],
        publishedBy: "Community",
        publishedWhen: "14/01/2024, 01:38",
        prerequisites: ["Basic Arduino Knowledge"],
        resources: ["https://www.youtube.com/watch?v=hNmacZoweqY"],
        hashtag: "#cl-iot-motiondetector",
      },
      {
        id: "4-8",
        title: "Controlling Servo Motor",
        desc: "In this task, you are required to connect to a Servo Motor and learn how to control it using Arduino in the Wowki simulator.\n\n🔗 Check out: https://www.youtube.com/watch?v=C_pWNQ6H9EE\n\nAfter completing this task, share the project URL in the ⁠internet-of-things-iot-and-robo… channel using the hashtag **#cl-iot-controllingservomotor** to avail ⭐ 50 karma points.",
        brief:
          "Learn to control precise movements with servo motors using Arduino for robotics applications.",
        ig: "IoT",
        icon: <MdSettingsRemote />,
        skills: ["Servo Control", "Motor Programming", "Precision Movement"],
        publishedBy: "Community",
        publishedWhen: "14/01/2024, 02:31",
        prerequisites: ["Basic Arduino Knowledge"],
        resources: ["https://www.youtube.com/watch?v=C_pWNQ6H9EE"],
        hashtag: "#cl-iot-controllingservomotor",
      },
      {
        id: "4-9",
        title: "Displaying Sensor Readings",
        desc: "In this task, you are required to show readings from a sensor on an LCD using Arduino in the Wowki simulator.\n\n🔗 Check out: https://www.youtube.com/watch?v=DzNZdEH916I\n\nAfter completing this task, share the project URL in the ⁠internet-of-things-iot-and-robo… channel using the hashtag **#cl-iot-lcdsensorreading** to avail ⭐ 50 karma points.",
        brief:
          "Build a data display system that shows sensor readings on an LCD screen with Arduino.",
        ig: "IoT",
        icon: <MdMonitor />,
        skills: ["LCD Interfacing", "Data Visualization", "User Interface"],
        publishedBy: "Community",
        publishedWhen: "14/01/2024, 03:33",
        prerequisites: ["Basic Arduino Knowledge"],
        resources: ["https://www.youtube.com/watch?v=DzNZdEH916I"],
        hashtag: "#cl-iot-lcdsensorreading",
      },
      {
        id: "4-10",
        title: "Automated Room Lighting System",
        desc: "You are required to build an automatic lighting system that turns on in the dark and off in bright conditions using Arduino, a light-dependent resistor (LDR), and an LED (or LED strip)\n\n📌NOTE: You can use real devices or an online simulator.\n\nAfter completing this project, share the project URL or a short video of your project in the ⁠internet-of-things-iot-and-robo… channel using the hashtag **#cl-iot-lightingsystem** to avail ⭐ 200 karma points.",
        brief:
          "Design a smart lighting system that automatically adjusts based on ambient light conditions for energy efficiency.",
        ig: "IoT",
        icon: <MdHome />,
        skills: ["Home Automation", "Smart Lighting", "Energy Efficiency"],
        publishedBy: "Community",
        publishedWhen: "14/01/2024, 03:58",
        prerequisites: ["Arduino Programming", "LDR Sensors"],
        resources: [],
        hashtag: "#cl-iot-lightingsystem",
      },
      {
        id: "4-11",
        title: "Basic Security System",
        desc: "You must design a simple security system that sounds an alarm when any motion is detected. Use Arduino, Passive Infrared (PIR) Sensor, Buzzer, and LED indicators.\n\n📌NOTE: You can use real devices or an online simulator.\n\nAfter completing this project, share the project URL or a short video of your project in the ⁠internet-of-things-iot-and-robo… channel using the hashtag **#cl-iot-securitysystem** to avail ⭐ 200 karma points.",
        brief:
          "Build a basic security system with motion detection, alarm, and visual indicators for home safety.",
        ig: "IoT",
        icon: <MdSecurity />,
        skills: ["Security Systems", "Alert Mechanisms", "Sensor Integration"],
        publishedBy: "Community",
        publishedWhen: "15/01/2024, 03:31",
        prerequisites: ["Arduino Programming", "PIR Sensors"],
        resources: [],
        hashtag: "#cl-iot-securitysystem",
      },
    ],
  },
];

export default levelsDataIOT;
