import React from "react";
import {
  MdEdit,
  MdCalculate,
  MdFunctions,
  MdDirectionsCar,
  MdLock,
  MdCode,
  MdDateRange,
  MdPhoto,
  MdMenuBook,
  MdFlight,
  MdLocationCity,
  MdSchool,
  MdArchitecture,
  MdHttp,
  MdStorage,
  MdWork,
  MdCompare,
  MdAccessTime,
  MdShoppingCart,
  MdFormatQuote,
  MdVpnKey,
  MdNumbers,
  MdMusicNote,
  MdEncryption,
} from "react-icons/md";

const levelsDataMOB = [
  {
    level: 4,
    title: "Level 4",
    subtitle: "Mobile Development Fundamentals",
    leveller: {
      id: "4-1",
      title: "The Story of Me",
      desc: "In this task, you have to create an interactive and user-friendly Dart program that allows users to input their personal information and generates a formatted and visually appealing biodata. You can format it as a text-based document, using line breaks to enhance readability.\n\n📌 The information to collect should include:\nName\nPhone number\nAge\nHeight\nWeight\nAddress\nHobbies (can be a list of hobbies)\n\n🔗 Reference: https://medium.com/geekculture/dart-programming-tutorial-variables-and-data-types-87440ee1ea94\n\nAfter completing this task, share the hosted GitHub URL in the ⁠mobile-development channel using the hashtag **#cl-dart-story** to avail ⭐ 100 karma points.",
      brief:
        "Create an interactive Dart program that collects and formats personal information into a visually appealing biodata display.",
      ig: "Mobile Development",
      icon: <MdEdit />,
      skills: ["Dart Programming", "User Input", "Text Formatting"],
      publishedBy: "Community",
      publishedWhen: "31/10/2023, 17:34",
      prerequisites: ["Basic Programming"],
      resources: [
        "https://medium.com/geekculture/dart-programming-tutorial-variables-and-data-types-87440ee1ea94",
      ],
      hashtag: "#cl-dart-story",
    },
    cards: [
      {
        id: "4-1",
        title: "The Story of Me",
        desc: "In this task, you have to create an interactive and user-friendly Dart program that allows users to input their personal information and generates a formatted and visually appealing biodata. You can format it as a text-based document, using line breaks to enhance readability.\n\n📌 The information to collect should include:\nName\nPhone number\nAge\nHeight\nWeight\nAddress\nHobbies (can be a list of hobbies)\n\n🔗 Reference: https://medium.com/geekculture/dart-programming-tutorial-variables-and-data-types-87440ee1ea94\n\nAfter completing this task, share the hosted GitHub URL in the ⁠mobile-development channel using the hashtag **#cl-dart-story** to avail ⭐ 100 karma points.",
        brief:
          "Create an interactive Dart program that collects and formats personal information into a visually appealing biodata display.",
        ig: "Mobile Development",
        icon: <MdEdit />,
        skills: ["Dart Programming", "User Input", "Text Formatting"],
        publishedBy: "Community",
        publishedWhen: "31/10/2023, 17:34",
        prerequisites: ["Basic Programming"],
        resources: [
          "https://medium.com/geekculture/dart-programming-tutorial-variables-and-data-types-87440ee1ea94",
        ],
        hashtag: "#cl-dart-story",
      },
      {
        id: "4-2",
        title: "Sum it Up",
        desc: 'In this task you have to create an interactive and user-friendly Dart program that accepts two numbers from the user as input, calculates their sum, and displays the result and message together by using string interpolation and concatenation.\n\n🔗 Reference: https://medium.com/geekculture/dart-programming-tutorial-string-interpolation-and-concatenation-c512a6cd9286\n📌NOTE: The message should be of the format:\n"The sum of [number1] and [number2] is [sum]"\n\nAfter completing this task, share the hosted GitHub URL in the ⁠mobile-development channel using the hashtag **#cl-dart-sum** to avail ⭐ 100 karma points.',
        brief:
          "Develop a Dart program that calculates the sum of two numbers and displays the result using string interpolation techniques.",
        ig: "Mobile Development",
        icon: <MdCalculate />,
        skills: ["String Interpolation", "Basic Arithmetic", "User Input"],
        publishedBy: "Community",
        publishedWhen: "31/10/2023, 18:01",
        prerequisites: ["Basic Dart Knowledge"],
        resources: [
          "https://medium.com/geekculture/dart-programming-tutorial-string-interpolation-and-concatenation-c512a6cd9286",
        ],
        hashtag: "#cl-dart-sum",
      },
      {
        id: "4-3",
        title: "BasiCulator",
        desc: "In this task, you have to create a menu-driven, interactive, and user-friendly Dart program that allows users to perform basic arithmetic and comparison operations using a calculator-like interface by accepting inputs from users and calculating results. Add comments and documentation to your code to explain how the program works and how users can interact with it.\n\n🔗 Reference: https://medium.com/geekculture/dart-programming-tutorial-basic-operators-663bab979b01\n\nAfter completing this task, share the hosted GitHub URL in the ⁠mobile-development channel using the hashtag **#cl-dart-basiculator** to avail ⭐ 100 karma points.",
        brief:
          "Build a menu-driven calculator program in Dart that performs arithmetic and comparison operations with proper documentation.",
        ig: "Mobile Development",
        icon: <MdCalculate />,
        skills: ["Menu Design", "Operators", "Code Documentation"],
        publishedBy: "Community",
        publishedWhen: "31/10/2023, 22:13",
        prerequisites: ["Dart Basics"],
        resources: [
          "https://medium.com/geekculture/dart-programming-tutorial-basic-operators-663bab979b01",
        ],
        hashtag: "#cl-dart-basiculator",
      },
      {
        id: "4-4",
        title: "Sumplier Madness",
        desc: "In this task, you are required to create an engaging and interactive program in Dart that helps students learn multiplication tables and practice their mathematical skills. Add comments and documentation to your code to explain how the program works and how users can interact with it.\n\n📌 Your program should perform the following tasks:\nPrompt the user to enter a number.\nGenerate a multiplication table for the first 10 multiples of that number.\nCompute the sum of all the numbers in the generated table.\n\n🔗 Reference: https://medium.com/geekculture/dart-programming-tutorial-loops-6ba26863aafd\n\nAfter completing this task, share your hosted GitHub or GitLab URL in the ⁠mobile-development channel using the hashtag **#cl-dart-sumplier** to avail ⭐ 100 karma points.",
        brief:
          "Create an educational Dart program that generates multiplication tables and calculates the sum of the products.",
        ig: "Mobile Development",
        icon: <MdFunctions />,
        skills: ["Loops", "Mathematical Operations", "Educational Programming"],
        publishedBy: "Community",
        publishedWhen: "02/11/2023, 01:29",
        prerequisites: ["Loops in Dart"],
        resources: [
          "https://medium.com/geekculture/dart-programming-tutorial-loops-6ba26863aafd",
        ],
        hashtag: "#cl-dart-sumplier",
      },
      {
        id: "4-5",
        title: "Function Fusioner",
        desc: "In this task, you are required to create a dynamic program in Dart that controls the capabilities of functions and lists to manipulate and organize data. Your program should feature a function that takes a list of numbers as a parameter that performs a specific operation on each element of the list and displays the output of each operation. Add comments and documentation to explain how to use your program effectively.\n\n🔗 Reference: https://medium.com/geekculture/dart-programming-tutorial-functions-4c37a7e8a674\n\n📌Step 1: Implement a Dart program that defines a function named processList which takes two parameters:\nA list of numbers (e.g., List<int> numbers).\nA function that represents an operation (e.g., (int number) => number * 2).\n\n📌Step 2: Inside the processList function, use a loop or iteration to apply the provided operation to each list element, and display the output for each element.\n\n📌Step 3: Create multiple instances of the processList function with different operations (e.g., one that doubles numbers, one that squares them, etc.).\n\n📌Step 4: Invoke these instances of the processList function with different lists of numbers to demonstrate your program's dynamic data manipulation capabilities.\n\nAfter completing this task, share the hosted GitHub or GitLab URL in the ⁠mobile-development channel using the hashtag **#cl-dart-fusioner** to avail ⭐ 100 karma points.",
        brief:
          "Develop a Dart program showcasing functional programming with higher-order functions that process lists with different operations.",
        ig: "Mobile Development",
        icon: <MdFunctions />,
        skills: [
          "Higher-Order Functions",
          "List Manipulation",
          "Functional Programming",
        ],
        publishedBy: "Community",
        publishedWhen: "04/11/2023, 01:09",
        prerequisites: ["Functions in Dart"],
        resources: [
          "https://medium.com/geekculture/dart-programming-tutorial-functions-4c37a7e8a674",
        ],
        hashtag: "#cl-dart-fusioner",
      },
      {
        id: "4-6",
        title: "Vroom Companion",
        desc: "In this task, you have to create a simple car buying and selling platform using object-oriented programming in Dart. Add comments and documentation that explain the working of your code. The platform should consist of two classes: Car and Person.\n\n🔹The Car class should have the following properties and methods:\nname\nprice\nchangePrice(newPrice)\n\n🔹The Person class should have the following properties and methods:\nname\nownedCars\nmoneyLeft\nbuyCar(car)\nsellCar(car)\n\n🔗 Reference: https://medium.com/geekculture/dart-programming-tutorial-object-oriented-programming-using-classes-48be44cbe095\n📌NOTE: Ensure that the properties ownedCars and moneyLeft are updated after the use of buyCar(car) and sellCar(car) methods.\n\nAfter completing this task, share the hosted GitHub or GitLab URL in the ⁠mobile-development channel using the hashtag **#cl-dart-vroom** to avail ⭐⭐ 400 karma points.",
        brief:
          "Build a car buying and selling simulation in Dart using object-oriented programming principles with Car and Person classes.",
        ig: "Mobile Development",
        icon: <MdDirectionsCar />,
        skills: [
          "Object-Oriented Programming",
          "Class Implementation",
          "State Management",
        ],
        publishedBy: "Community",
        publishedWhen: "04/11/2023, 02:04",
        prerequisites: ["OOP in Dart"],
        resources: [
          "https://medium.com/geekculture/dart-programming-tutorial-object-oriented-programming-using-classes-48be44cbe095",
        ],
        hashtag: "#cl-dart-vroom",
      },
      {
        id: "4-7",
        title: "Lock and Key",
        desc: "In this task, you have to build a class that can perform password operations in Dart. It should include functions to validate the strength of a password and generate passwords in three different levels: strong, intermediate, and low. Add comments and documentation for code clarity.\n\n🔗 Reference: https://dart.academy/writing-command-line-utilities-with-dart/\n\nAfter completing this task, share the hosted GitHub or GitLab URL in the ⁠mobile-development channel using the hashtag **#cl-dart-lockandkey** to avail ⭐⭐ 400 karma points.",
        brief:
          "Create a password utility class in Dart that can validate password strength and generate passwords of varying security levels.",
        ig: "Mobile Development",
        icon: <MdLock />,
        skills: [
          "Security Programming",
          "Password Management",
          "String Manipulation",
        ],
        publishedBy: "Community",
        publishedWhen: "04/11/2023, 03:05",
        prerequisites: ["Classes in Dart"],
        resources: [
          "https://dart.academy/writing-command-line-utilities-with-dart/",
        ],
        hashtag: "#cl-dart-lockandkey",
      },
      {
        id: "4-8",
        title: "Dart Coding Challenges",
        desc: "In this task, you have to complete all the coding exercises of Dart given in Exercism. This will help you gain practical knowledge on Dart.\n\n🔗 Check out: https://exercism.org/tracks/dart\n\nAfter completing 10 challenges, share your profile URL and a screenshot of your progress in the ⁠mobile-development channel using the hashtag **#cl-dart-exercism-10** to avail the first ⭐ 200 karma points.\n\nAfter completing 20 challenges, share your profile URL and a screenshot of your progress in the ⁠mobile-development channel using the hashtag **#cl-dart-exercism-20** to avail the next ⭐ 200 karma points.\n\nAfter completing 30 challenges, share your profile URL and a screenshot of your progress in the ⁠mobile-development channel using the hashtag **#cl-dart-exercism-30** to avail the next ⭐ 200 karma points.\n\nAfter completing all 41 challenges, share your profile URL and a screenshot of your progress in the ⁠mobile-development channel using the hashtag **#cl-dart-exercism-41** to avail the remaining ⭐ 200 karma points.",
        brief:
          "Enhance your Dart programming skills by completing a series of increasingly challenging exercises on Exercism.",
        ig: "Mobile Development",
        icon: <MdCode />,
        skills: ["Problem Solving", "Algorithm Design", "Dart Mastery"],
        publishedBy: "Community",
        publishedWhen: "04/11/2023, 03:23",
        prerequisites: ["Basic Dart Knowledge"],
        resources: ["https://exercism.org/tracks/dart"],
        hashtag: "#cl-dart-exercism-10",
      },
      {
        id: "4-9",
        title: "30 Days App",
        desc: "In this task, you have to build a 30 Days App using the provided resources and design it to help users track and achieve their goals and challenges for 30 days. Add features and functions such as setting and tracking goals, progress tracking, reminders, and motivational content, to make the app more engaging for the users. Ensure that the app follows modern Android app design principles.\n\n🔗 Check out: https://developer.android.com/codelabs/basic-android-kotlin-compose-30-days\n\nAfter completing this task, share the hosted GitHub repository URL in the ⁠mobile-development channel using the hashtag **#cl-android-30app** to avail ⭐ 50 karma points.",
        brief:
          "Develop an Android app that helps users set and track 30-day challenges with progress tracking and motivational features.",
        ig: "Mobile Development",
        icon: <MdDateRange />,
        skills: ["Android Development", "Kotlin", "UI/UX Design"],
        publishedBy: "Community",
        publishedWhen: "04/11/2023, 03:47",
        prerequisites: ["Android Basics"],
        resources: [
          "https://developer.android.com/codelabs/basic-android-kotlin-compose-30-days",
        ],
        hashtag: "#cl-android-30app",
      },
      {
        id: "4-10",
        title: "Art Space App",
        desc: "In this task, you have to build an Art Space App using the provided resources and develop an app that caters to art enthusiasts, allowing them to explore and appreciate various forms of art. Add features and functions such as browsing and viewing art collections, learning about other artists, and art history, and creating their own virtual galleries, to make the app more engaging for the users. Ensure that the app follows modern Android app design principles.\n\n🔗 Check out: https://developer.android.com/codelabs/basic-android-kotlin-compose-art-space\n\nAfter completing this task, share the hosted GitHub repository URL in the ⁠mobile-development channel using the hashtag **#cl-android-artspace** to avail ⭐ 50 karma points.",
        brief:
          "Create an Android app for art enthusiasts to browse collections, learn about artists, and curate virtual galleries.",
        ig: "Mobile Development",
        icon: <MdPhoto />,
        skills: ["Jetpack Compose", "Image Handling", "Gallery Design"],
        publishedBy: "Community",
        publishedWhen: "05/11/2023, 02:02",
        prerequisites: ["Android Development"],
        resources: [
          "https://developer.android.com/codelabs/basic-android-kotlin-compose-art-space",
        ],
        hashtag: "#cl-android-artspace",
      },
      {
        id: "4-11",
        title: "Bookshelf App",
        desc: "In this task, you have to build a Bookshelf App using the provided resources that allow users to manage and organize their digital book collection. They should be able to add, remove, and categorize books on their shelf. Add features and functions such as searching for books, sorting by genre or author, and tracking reading progress, to make it more engaging. Ensure that the app follows modern Android app design principles.\n\n🔗 Check out: https://developer.android.com/codelabs/basic-android-kotlin-compose-bookshelf\n\nAfter completing this task, share the hosted GitHub repository URL in the ⁠mobile-development channel using the hashtag **#cl-android-bookshelf** to avail ⭐ 100 karma points.",
        brief:
          "Build a digital bookshelf app for Android that allows users to manage, categorize, search, and track reading progress.",
        ig: "Mobile Development",
        icon: <MdMenuBook />,
        skills: ["API Integration", "Data Management", "Search Implementation"],
        publishedBy: "Community",
        publishedWhen: "05/11/2023, 02:26",
        prerequisites: ["Android Development"],
        resources: [
          "https://developer.android.com/codelabs/basic-android-kotlin-compose-bookshelf",
        ],
        hashtag: "#cl-android-bookshelf",
      },
      {
        id: "4-12",
        title: "Flight Search App",
        desc: "In this task, you have to build a Flight Search App using the provided resources that allow users to search for flights based on various criteria such as departure city, destination, date, etc. Add features and functions such as filtering and sorting, displaying flight details, and providing booking options, to make it more engaging. Ensure that the app follows modern Android app design principles.\n\n🔗 Check out: https://developer.android.com/codelabs/basic-android-kotlin-compose-flight-search\n\nAfter completing this task, share the hosted GitHub repository URL in the ⁠mobile-development channel using the hashtag **#cl-android-flight** to avail ⭐ 100 karma points.",
        brief:
          "Develop a flight search app with advanced filtering, sorting, and booking features using modern Android design principles.",
        ig: "Mobile Development",
        icon: <MdFlight />,
        skills: ["Search Functionality", "Filtering", "Database Management"],
        publishedBy: "Community",
        publishedWhen: "05/11/2023, 22:54",
        prerequisites: ["Room Database", "Android Development"],
        resources: [
          "https://developer.android.com/codelabs/basic-android-kotlin-compose-flight-search",
        ],
        hashtag: "#cl-android-flight",
      },
      {
        id: "4-13",
        title: "My City App",
        desc: "In this task, you have to build a My City App using the provided resources providing useful information about your city such as tourist attractions, restaurants, events, etc. Add features and functions like searching for places of interest, viewing details about attractions, and accessing maps for navigation, to make it more engaging. Ensure that the app follows modern Android app design principles.\n\n🔗 Check out: https://developer.android.com/codelabs/basic-android-kotlin-compose-my-city\n\nAfter completing this task, share the hosted GitHub repository URL in the ⁠mobile-development channel using the hashtag **#cl-android-mycity** to avail ⭐ 100 karma points.",
        brief:
          "Create a city guide app showcasing attractions, restaurants, and events with search functionality and map integration.",
        ig: "Mobile Development",
        icon: <MdLocationCity />,
        skills: ["Navigation Component", "Location Services", "Local Database"],
        publishedBy: "Community",
        publishedWhen: "06/11/2023, 00:19",
        prerequisites: ["Android Development"],
        resources: [
          "https://developer.android.com/codelabs/basic-android-kotlin-compose-my-city",
        ],
        hashtag: "#cl-android-mycity",
      },
      {
        id: "4-14",
        title: "Android Basics with Compose Unit 1",
        desc: 'In this task, you will learn programming basics and create your first Android app. You will familiarize yourself with the basics of Android app development and understand the Android ecosystem, development tools, and the structure of Android apps. It could be a simple "Hello World" app or a basic calculator. The goal is to apply what you\'ve learned. Test your app on an Android emulator or a physical device to ensure it works as intended.\n\n📌NOTE: Provide a link to your Google Developer Profile or any relevant certifications or badges related to Android app development.\n\nAfter completing this task, share the hosted GitHub repository URL in the ⁠mobile-development channel using the hashtag **#cl-android-unit1** to avail ⭐ 100 karma points.',
        brief:
          "Build your first Android app while learning the fundamentals of the Android ecosystem and development tools.",
        ig: "Mobile Development",
        icon: <MdSchool />,
        skills: ["Android Basics", "Android Studio", "App Structure"],
        publishedBy: "Community",
        publishedWhen: "06/11/2023, 00:32",
        prerequisites: ["None"],
        resources: [],
        hashtag: "#cl-android-unit1",
      },
      {
        id: "4-15",
        title: "Android Basics with Compose Unit 2",
        desc: "In this task, you will continue learning the fundamentals of Kotlin and start building another interactive Android app. Choose a project or app idea that involves building interactivity. It could be a basic calculator, a quiz app, a simple game, or any other concept that interests you. Ensure that the app provides user feedback and engages users in meaningful interactions. Test your app thoroughly to verify its functionality and interactivity.\n\n📌NOTE: Provide a link to your Google Developer Profile or any relevant certifications or badges related to Kotlin programming and Android app development.\n\nAfter completing this task, share the hosted GitHub repository URL in the ⁠mobile-development channel using the hashtag **#cl-android-unit2** to avail ⭐ 100 karma points.",
        brief:
          "Create an interactive Android app like a calculator, quiz, or game focusing on user engagement and feedback.",
        ig: "Mobile Development",
        icon: <MdSchool />,
        skills: ["Interactive UI", "Kotlin", "User Feedback"],
        publishedBy: "Community",
        publishedWhen: "06/11/2023, 00:50",
        prerequisites: ["Android Unit 1"],
        resources: [],
        hashtag: "#cl-android-unit2",
      },
      {
        id: "4-16",
        title: "Android Basics with Compose Unit 3",
        desc: "In this task, you have to build apps that display a list of data and enhance their visual appeal with Material Design principles. Familiarize yourself with guidelines related to layouts, color schemes, typography, and elevation. Your app could be a simple to-do list, a news feed, a list of products, or any other topic that interests you. Design and build your app using Material Design components and principles. Test your app to ensure that it effectively displays a list of data and adheres to Material Design guidelines.\n\n📌NOTE: Provide a link to your Google Developer Profile or any relevant certifications or badges related to Android app development.\n\nAfter completing this task, share the hosted GitHub repository URL in the ⁠mobile-development channel using the hashtag **#cl-android-unit3** to avail ⭐ 100 karma points.",
        brief:
          "Design a data-driven app implementing Material Design principles for layouts, color schemes, and typography.",
        ig: "Mobile Development",
        icon: <MdSchool />,
        skills: ["Material Design", "List Handling", "UI Components"],
        publishedBy: "Community",
        publishedWhen: "06/11/2023, 01:21",
        prerequisites: ["Android Unit 2"],
        resources: [],
        hashtag: "#cl-android-unit3",
      },
      {
        id: "4-17",
        title: "Android Basics with Compose Unit 4",
        desc: "In this task, you will learn the best practices of app architecture to build more complex apps. Explore architecture principles like architectural patterns like MVVM, MVI, MVP, and others. Create a document or presentation where you summarize your findings about app architecture best practices that includes information about the chosen architectural pattern, separation of concerns, data binding, and any other relevant topics.\n\n📌NOTE: Provide a link to your Google Developer Profile or any relevant certifications or badges related to Android app architecture.\n\nAfter completing this task, share your document/presentation in the ⁠mobile-development channel using the hashtag **#cl-android-unit4** to avail ⭐ 100 karma points.",
        brief:
          "Research and document Android app architecture patterns like MVVM, MVI, and MVP with practical implementation insights.",
        ig: "Mobile Development",
        icon: <MdArchitecture />,
        skills: ["App Architecture", "Design Patterns", "Documentation"],
        publishedBy: "Community",
        publishedWhen: "06/11/2023, 01:42",
        prerequisites: ["Android Unit 3"],
        resources: [],
        hashtag: "#cl-android-unit4",
      },
      {
        id: "4-18",
        title: "Android Basics with Compose Unit 5",
        desc: "In this task, you have to create a new Android project and implement fetching data from the internet and displaying images. Implement Kotlin Coroutines to perform network requests using Retrofit to fetch data from a public API. Use the Coil library to efficiently load and display images in your app's UI. Test your app to ensure that it can fetch data from the internet and display images as intended.\n\n📌NOTE: Provide a link to your Google Developer Profile to showcase your badges or certifications related to Android development.\n\nAfter completing this task, share the hosted GitHub repository URL in the ⁠mobile-development channel using the hashtag **#cl-android-unit5** to avail ⭐ 100 karma points.",
        brief:
          "Build an Android app that fetches data from APIs using Kotlin Coroutines, Retrofit, and displays images with Coil.",
        ig: "Mobile Development",
        icon: <MdHttp />,
        skills: ["Network Requests", "Coroutines", "API Integration"],
        publishedBy: "Community",
        publishedWhen: "06/11/2023, 02:39",
        prerequisites: ["Android Unit 4"],
        resources: [],
        hashtag: "#cl-android-unit5",
      },
      {
        id: "4-19",
        title: "Android Basics with Compose Unit 6",
        desc: "In this task, you will learn how to store data locally on the device for a smooth and consistent user experience. Review Android documentation and resources related to data storage options including SharedPreferences, SQLite Database, and other local storage methods. Create a new app where you can choose to store various types of data such as user preferences, application settings, and other relevant data. Test the local data storage features in your app to ensure they work as intended.\n\n📌NOTE: Provide a link to your Google Developer Profile to showcase your badges or certifications related to Android development.\n\nAfter completing this task, share the hosted GitHub repository URL in the ⁠mobile-development channel using the hashtag **#cl-android-unit6** to avail ⭐ 100 karma points.",
        brief:
          "Implement local data storage in Android using SharedPreferences, SQLite Database, and other persistence options.",
        ig: "Mobile Development",
        icon: <MdStorage />,
        skills: ["Local Storage", "SQLite", "SharedPreferences"],
        publishedBy: "Community",
        publishedWhen: "06/11/2023, 02:59",
        prerequisites: ["Android Unit 5"],
        resources: [],
        hashtag: "#cl-android-unit6",
      },
      {
        id: "4-20",
        title: "Android Basics with Compose Unit 7",
        desc: "In this task, you will learn to use Android Jetpack's WorkManager API and understand how it can be used for scheduling background work. Create an app that does tasks like periodic data synchronization, notifications, or any other background operation. Test and validate that the background work is being scheduled and executed correctly.\n\n📌NOTE: Provide a link to your Google Developer Profile to showcase your badges or certifications related to Android development.\n\nAfter completing this task, share the hosted GitHub repository URL in the ⁠mobile-development channel using the hashtag **#cl-android-unit7** to avail ⭐ 100 karma points.",
        brief:
          "Create an Android app with background processing capabilities using Jetpack's WorkManager for tasks like synchronization.",
        ig: "Mobile Development",
        icon: <MdWork />,
        skills: ["WorkManager", "Background Processing", "Scheduler"],
        publishedBy: "Community",
        publishedWhen: "06/11/2023, 03:27",
        prerequisites: ["Android Unit 6"],
        resources: [],
        hashtag: "#cl-android-unit7",
      },
      {
        id: "4-21",
        title: "Android Basics with Compose Unit 8",
        desc: "In this task, you will learn how to use Jetpack Compose and the older UI toolkit based on Views and create an app that incorporates both of these into the same app. You can choose to create a simple app or explore more complex scenarios based on your learning goals. Implement UI components using Jetpack Compose and View-based UI Toolkit (XML layouts and View widgets) in your app. Test your app and check its validity.\n\n📌NOTE: Provide a link to your Google Developer Profile to showcase your badges or certifications related to Android development.\n\nAfter completing this task, share the hosted GitHub repository URL in the ⁠mobile-development channel using the hashtag **#cl-android-unit8** to avail ⭐ 100 karma points.",
        brief:
          "Create an app that combines Jetpack Compose with traditional View-based layouts to understand both UI paradigms.",
        ig: "Mobile Development",
        icon: <MdCompare />,
        skills: ["Jetpack Compose", "View-Based UI", "Interoperability"],
        publishedBy: "Community",
        publishedWhen: "06/11/2023, 03:59",
        prerequisites: ["Android Unit 7"],
        resources: [],
        hashtag: "#cl-android-unit8",
      },
      {
        id: "4-22",
        title: "Clock App",
        desc: "In this task, you have to create a visually appealing Android Clock App that includes both analog and digital display options, along with Alarm, Stopwatch, and Timer functionalities.\n\n🔹Step 1: Design the main screen that includes 2 options: Analog Clock Display and Digital Clock Display. Navigation tabs to switch between Alarm, Stopwatch, and Timer.\n\n🔹Step 2: Allow users to set alarms with a specific time and repeat options. Add options such as edit, and delete alarms. Trigger alarm notifications even when the app is running in the background or closed.\n\n🔹Step 3: Include stopwatch functionalities such as start, pause, and reset. Display elapsed time in hours, minutes, seconds, and milliseconds.\n\n🔹Step 4: Allow users to set countdown timers with specific duration. Include options such as start, pause, resume, and cancel timers. Display remaining time in hours, minutes, and seconds.\n\n🔹Step 5: Test the app thoroughly to ensure that all clock functionalities work as expected.\n\n📌NOTE: Provide clear instructions on how to use the Alarm, Stopwatch, and Timer functionalities within the app in the README.\n\nAfter completing this task, share the hosted GitHub repository URL and a screenshot of your app in the ⁠mobile-development channel using the hashtag **#cl-android-clock** to avail ⭐ 200 karma points.",
        brief:
          "Build a comprehensive clock application with analog and digital displays plus alarm, stopwatch, and timer functions.",
        ig: "Mobile Development",
        icon: <MdAccessTime />,
        skills: ["Time Management", "Notifications", "UI Design"],
        publishedBy: "Community",
        publishedWhen: "06/11/2023, 18:43",
        prerequisites: ["Android Development"],
        resources: [],
        hashtag: "#cl-android-clock",
      },
      {
        id: "4-23",
        title: "Amazon UI Clone",
        desc: "In this task, you have to develop an Android application that replicates the user interface (UI) of Amazon by creating a visually appealing Amazon-like experience without actual e-commerce functionality. Ensure the UI is adaptive to different screen sizes.\n\n🔹Step 1: Replicate the key features and components of the Amazon app such as:\nA product feed displaying products with images, titles, prices, and ratings.\nA navigation drawer or bottom navigation for different app sections.\nProduct details pages with larger images, descriptions, and related products.\nA shopping cart or basket page displaying selected products.\nA user profile section with order history and account information.\n\n🔹Step 2: Pay attention to the design and layout to closely resemble the Amazon app. Ensure that the UI is visually appealing and user-friendly.\n\n🔹Step 3: Implement sample data or use placeholder images and text to populate the product feed and product details pages.\n\n🔹Step 4: Implement navigation between different sections of the app, such as the product feed, product details, and shopping cart.\n\n🔹Step 5: Test the app thoroughly to verify that it accurately replicates the Amazon-like UI and provides a smooth user experience.\n\n📌NOTE: Provide clear instructions on how to navigate and interact with the Amazon Clone UI in the README.\n\nAfter completing this task, share the hosted GitHub repository URL and a screenshot of your app in the ⁠mobile-development channel using the hashtag **#cl-android-amazon** to avail ⭐ 200 karma points.",
        brief:
          "Create an Amazon app clone focusing on UI/UX design with product listings, navigation, details pages, and shopping cart.",
        ig: "Mobile Development",
        icon: <MdShoppingCart />,
        skills: ["UI Design", "Navigation Components", "Adaptive Layouts"],
        publishedBy: "Community",
        publishedWhen: "06/11/2023, 20:57",
        prerequisites: ["Android Development", "RecyclerView"],
        resources: [],
        hashtag: "#cl-android-amazon",
      },
      {
        id: "4-24",
        title: "Pangram",
        desc: "In this task, you have to figure out if a sentence is a pangram or not. Complete all the tasks until you see 100% completion.\n\n🔗 Check out: https://exercism.org/tracks/kotlin/exercises/pangram\n\nAfter completing this task, share your profile URL and a screenshot of your progress in the ⁠mobile-development channel using the hashtag **#cl-kotlin-pangram** to avail ⭐ 50 karma points.",
        brief:
          "Implement an algorithm to determine if a given sentence contains every letter of the alphabet.",
        ig: "Mobile Development",
        icon: <MdFormatQuote />,
        skills: ["String Manipulation", "Kotlin Programming", "Algorithms"],
        publishedBy: "Community",
        publishedWhen: "06/11/2023, 21:33",
        prerequisites: ["Basic Kotlin"],
        resources: ["https://exercism.org/tracks/kotlin/exercises/pangram"],
        hashtag: "#cl-kotlin-pangram",
      },
      {
        id: "4-25",
        title: "Crypto Square",
        desc: "In this task, you will learn the basics of Crypto Square a method used to convert plain English text to a secret message. Complete all the tasks provided until you see a 100% completion status.\n\n🔗 Check out: https://exercism.org/tracks/kotlin/exercises/crypto-square\n\nAfter completing this task, share your profile URL and a screenshot of your progress in the ⁠mobile-development channel using the hashtag **#cl-kotlin-cryptop** to avail ⭐ 50 karma points.",
        brief:
          "Implement the classic Crypto Square cipher to encrypt messages using transposition techniques.",
        ig: "Mobile Development",
        icon: <MdVpnKey />,
        skills: [
          "Cryptography",
          "Matrix Operations",
          "Algorithm Implementation",
        ],
        publishedBy: "Community",
        publishedWhen: "06/11/2023, 21:52",
        prerequisites: ["Kotlin Basics"],
        resources: [
          "https://exercism.org/tracks/kotlin/exercises/crypto-square",
        ],
        hashtag: "#cl-kotlin-cryptop",
      },
      {
        id: "4-26",
        title: "Perfect Numbers",
        desc: "In this task, you will learn how to determine if a number is perfect, abundant, or deficient based on the Nicomachus classification scheme for positive integers and how to implement this depending on your language track. Complete all the tasks provided until you see a 100% completion status.\n\n🔗 Check out: https://exercism.org/tracks/kotlin/exercises/perfect-numbers\n\nAfter completing this task, share your profile URL and a screenshot of your progress in the ⁠mobile-development channel using the hashtag **#cl-kotlin-perfectno** to avail ⭐ 50 karma points.",
        brief:
          "Write an algorithm to classify numbers as perfect, abundant, or deficient based on their aliquot sums.",
        ig: "Mobile Development",
        icon: <MdNumbers />,
        skills: [
          "Number Theory",
          "Mathematical Algorithms",
          "Kotlin Functions",
        ],
        publishedBy: "Community",
        publishedWhen: "06/11/2023, 22:17",
        prerequisites: ["Kotlin Basics"],
        resources: [
          "https://exercism.org/tracks/kotlin/exercises/perfect-numbers",
        ],
        hashtag: "#cl-kotlin-perfectno",
      },
      {
        id: "4-27",
        title: "Scale Generator",
        desc: "In this task, you will learn how to generate a musical scale and will be able to generate the musical scale starting with the tonic and following the specified interval pattern. Complete all the tasks provided until you see a 100% completion status.\n\n🔗 Check out: https://exercism.org/tracks/kotlin/exercises/scale-generator\n\nAfter completing this task, share your profile URL and a screenshot of your progress in the ⁠mobile-development channel using the hashtag **#cl-kotlin-scale** to avail ⭐ 50 karma points.",
        brief:
          "Create an application that can generate musical scales in various keys following specific interval patterns.",
        ig: "Mobile Development",
        icon: <MdMusicNote />,
        skills: ["Music Theory", "Pattern Generation", "Kotlin Collections"],
        publishedBy: "Community",
        publishedWhen: "06/11/2023, 22:45",
        prerequisites: ["Kotlin Basics"],
        resources: [
          "https://exercism.org/tracks/kotlin/exercises/scale-generator",
        ],
        hashtag: "#cl-kotlin-scale",
      },
      {
        id: "4-28",
        title: "Caesar Cipher",
        desc: "In this task, you have to implement a Caesar Cipher in Kotlin that can encrypt and decrypt text. Write a short README explaining how your code works.\n\n🔗 Check out: https://exercism.org/tracks/kotlin/exercises/rotational-cipher\n\nAfter completing this task, share your profile URL and a screenshot or GIF demonstrating the working of your code in the ⁠mobile-development channel using the hashtag **#cl-kotlin-caesar** to avail ⭐ 50 karma points.",
        brief:
          "Implement the classic Caesar cipher encryption algorithm to shift letters by a specified amount.",
        ig: "Mobile Development",
        icon: <MdEncryption />,
        skills: ["Encryption", "Character Manipulation", "Modular Arithmetic"],
        publishedBy: "Community",
        publishedWhen: "06/11/2023, 22:59",
        prerequisites: ["Kotlin Basics"],
        resources: [
          "https://exercism.org/tracks/kotlin/exercises/rotational-cipher",
        ],
        hashtag: "#cl-kotlin-caesar",
      },
    ],
  },
  {
    level: 5,
    title: "Level 5",
    subtitle: "Advanced Mobile Development",
    leveller: {
      id: "5-1",
      title: "Linked list Midpoint",
      desc: "In this task, you have to write a program that returns the 'middle' node of a linked list.\n\n🔗 Check out: https://github.com/igorwojda/kotlin-coding-challenges/tree/main/src/test/kotlin/com/igorwojda/linkedlist/singly/midpoint\n\nAfter completing this task, share the hosted GitHub repository URL in the ⁠mobile-development channel using the hashtag **#cl-kotlin-llmid** to avail ⭐ 50 karma points.",
      brief:
        "Implement an algorithm to find the middle node of a linked list efficiently.",
      ig: "Mobile Development",
      icon: <MdCode />,
      skills: ["Data Structures", "Linked Lists", "Two-Pointer Technique"],
      publishedBy: "Community",
      publishedWhen: "31/10/2023, 17:35",
      prerequisites: ["Data Structures", "Kotlin"],
      resources: [
        "https://github.com/igorwojda/kotlin-coding-challenges/tree/main/src/test/kotlin/com/igorwojda/linkedlist/singly/midpoint",
      ],
      hashtag: "#cl-kotlin-llmid",
    },
    cards: [
      // Level 5 cards would be here
    ],
  },
  {
    level: 6,
    title: "Level 6",
    subtitle: "Professional Mobile Development",
    leveller: {
      id: "6-1",
      title: "Forecasting with Flutter UI",
      desc: "In this task, you have to create a visually appealing and responsive mobile application UI for weather forecasting using Flutter. The UI should display current weather conditions and provide a multi-day forecast. Ensure the UI is user-friendly and adaptable to different screen sizes and orientations. Design the UI to be scalable, allowing for future enhancements and changes without significant redesign. You may use external libraries or assets for weather icons or images if needed.\n\n🔹The UI should contain the following elements:\nA header section displaying the current location and current temperature.\nAn icon or image representing the current weather condition (e.g., sunny, cloudy, rainy).\nA section displaying the forecast for the next few days. Include the date, high and low temperatures, and weather condition icon or image for each day.\n\n📌NOTE: Provide clear instructions on how to use the weather forecasting UI in the README.\n\nAfter completing this task, share the hosted GitHub repository URL in the ⁠mobile-development channel using the hashtag **#cl-flutter-forecastui** to avail ⭐⭐ 400 karma points.",
      brief:
        "Create a beautiful, responsive weather forecasting UI in Flutter that displays current conditions and multi-day forecasts.",
      ig: "Mobile Development",
      icon: <MdCloud />,
      skills: ["Flutter UI", "Responsive Design", "Weather Data Visualization"],
      publishedBy: "Community",
      publishedWhen: "31/10/2023, 17:35",
      prerequisites: ["Flutter Basics"],
      resources: [],
      hashtag: "#cl-flutter-forecastui",
    },
    cards: [
      // Level 6 cards would be here
    ],
  },
];

export default levelsDataMOB;
